### ISSUE TITLE
SSRP DNS 是否与 Turbo ACC DNS 有冲突？

### ISSUE THREAD

**Issue by moxuanyuan** [kiddin9/OpenWrt_x86-r2s-r4s#164]
K2P，已经刷了最新的10.16固件，SSRP DNS 与 Turbo ACC DNS 都是使用PDNSD ，重启路由后，SSRP显示 运行中，实测不能正常访问外国网站，需要手动重启 SSRP 才行。把SSRP 改为 DNS2SOCKS 后，重启路由才正常

**Comment by garypang13** [comment]
应该不存在冲突的, SSRP的PDNSD 用的是5335端口, Turbo ACC的PDNSD 用的是5333端口.

![image](https://user-images.githubusercontent.com/48883331/96333654-c8d14580-109d-11eb-9b9e-cdb0508e2743.png)

**Comment by moxuanyuan** [comment]
> 应该不存在冲突的, SSRP的PDNSD 用的是5335端口, Turbo ACC的PDNSD 用的是5333端口.
> 
> ![image](https://user-images.githubusercontent.com/48883331/96333654-c8d14580-109d-11eb-9b9e-cdb0508e2743.png)

再试了一下，应该不是跟Turbo ACC DNS 有冲突，SSRP 改为 DNS2SOCKS 重启后还是不能访问外国网站 ，需要手动重启 SSRP，请问，我应该怎样去debug？

**Comment by garypang13** [comment]
建议将ssr和turbo acc中的DNS都关掉,改用smartdns.
