### ISSUE TITLE
hc5962没完善么，编译菜单里木有

### ISSUE THREAD

**Issue by lee29** [kiddin9/OpenWrt_x86-r2s-r4s#166]
rt

**Comment by garypang13** [comment]
onekey一键编译脚本里吗?

**Comment by lee29** [comment]
> onekey一键编译脚本里吗?

是滴是滴

**Comment by garypang13** [comment]
已添加.

**Comment by lee29** [comment]
> 已添加.

make menuconfig界面nginx-mod-luci没有选上。uhttpd好像还是默认。
然后开始编译卡在make[2] -C tools/sed download这里咯

**Comment by garypang13** [comment]
@lee29 只有X86和R2S才是用的Nginx,其他硬路由都是用默认的uhttpd,

**Comment by TaihuLight** [comment]
@garypang13 
利用Breed刷您发布的Hiwifi-HC5962 (极路由4增强版)的固件openwrt-ramips-mt7621-hiwifi_hc5962-squashfs-sysupgrade.bin时，遇到错误“无法识别的固件类型”。请问有其他方法将您发布的固件成功刷到设备上的方法吗？是刷的方法不正确，还是您这次发布的固件有bug？
