### ISSUE TITLE
红米AC2100这个系统无法配置802.11s

### ISSUE THREAD

**Issue by freebattle** [kiddin9/OpenWrt_x86-r2s-r4s#169]
添加网络的时候没有无线配置的选项，但是刷机底包那个系统有这个选项

**Comment by garypang13** [comment]
刷机底包用的是官方的无线驱动
正式版用的是lean仓库的闭源驱动.

**Comment by jackadam1981** [comment]
看来和我的问题差不多，驱动不同，影响功能不同。
是不是应该为不同的驱动生成不同的刷机包呢？
