### ISSUE TITLE
在线安装提示ipk长度不匹配问题和内核版本不一致问题

### ISSUE THREAD

**Issue by ffii4455** [kiddin9/OpenWrt_x86-r2s-r4s#175]
只能通过ssh强行安装吗？

**Comment by garypang13** [comment]
更新列表, 内核版本不一致说明固件暂不支持此插件

**Comment by ffii4455** [comment]
vpnd也不支持吗？强制安装可以运行起来

**Comment by garypang13** [comment]
@ffii4455 vpnd并不会提示内核版本不一致

**Comment by ffii4455** [comment]
@garypang13 
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ipsec-vpnd:
 * 	kernel (= 5.4.72-1-581e3be1bf0df812542bd1683dc1ef03)
 * opkg_install_cmd: Cannot install package luci-app-ipsec-vpnd.

我用的是周更版本内核是5.4.72，应该自己编译一个最新的？

**Comment by garypang13** [comment]
是什么设备,我在x86设备上测试是可以正常安装luci-app-ipsec-vpnd

**Comment by ffii4455** [comment]
路由器，小米AC2100

**Comment by garypang13** [comment]
@ffii4455 ac2100下vpnd安装确实有问题,下一版修复.

**Comment by ffii4455** [comment]
谢谢大佬 @garypang13

**Comment by ffii4455** [comment]
@garypang13 大佬，实测opkg update后 长度报错依然存在。还请一起关注一下，谢谢！
Collected errors:
 * opkg_install_pkg: Package size mismatch: luci-app-openvpn-server is 21252 bytes, expecting 21257 bytes
 * opkg_install_cmd: Cannot install package luci-app-openvpn-server.

**Comment by garypang13** [comment]
新版已添加vpnd支持.

**Comment by IveanEx** [comment]
@garypang13 AC2100安装openclash也有一些问题，提示内核的版本不匹配。强制安装同样也没有任何问题

**Comment by garypang13** [comment]
> @garypang13 AC2100安装openclash也有一些问题，提示内核的版本不匹配。强制安装同样也没有任何问题

下一版修复
