### ISSUE TITLE
K2P没有无线mac过滤

### ISSUE THREAD

**Issue by jackadam1981** [kiddin9/OpenWrt_x86-r2s-r4s#188]
貌似是驱动版本的问题
可否自动编译一个带有mac过滤的固件呢？
K2有没有适配？

**Comment by garypang13** [comment]
软件包中搜索安装 luci-app-accesscontrol

**Comment by jackadam1981** [comment]
accesscontrol是上网时间控制，不是无线mac黑白名单。
[https://img-my.csdn.net/uploads/201610/07/1475840151_4648.gif](url)

**Comment by garypang13** [comment]
accesscontrol就是基于mac, mac为什么还要区分是有线还是无线

**Comment by jackadam1981** [comment]
一个是能连上无线，无法上网，一个是知道密码都无法连上。
