### ISSUE TITLE
请问下R2S如何换回默认的网口？

### ISSUE THREAD

**Issue by iii6** [kiddin9/OpenWrt_x86-r2s-r4s#191]
我的R2S用这个固件对换网口WAN插上去没有反应，用没有对换网口的固件就能用，请问下如何把网口对换回来？

**Comment by garypang13** [comment]
不建议换回来,交换网口对提升网速是有帮助的. https://youtu.be/wN_sE29Nh2M?t=136

**Comment by iii6** [comment]
@garypang13 现在是我插上网线R2S没有反应了啊，IP也进不去，而且对换了的WAN口绿灯不会亮。

**Comment by garypang13** [comment]
重刷,就保持默认,别交换网口了,

**Comment by iii6** [comment]
@garypang13 保持默认网口，WAN两个灯都不亮。昨晚上从刷了好几次都没用，还有另外一个也是换了网口的固件也不行，不换网口的固件能用，。

**Comment by garypang13** [comment]
那应该不会交换了网口导致的,是有不少用户用不了这个固件的,最有可能是电源的问题, 电压不够, 其次是TF卡,

**Comment by iii6** [comment]
@garypang13 这个我也不懂了，要是说TF卡有问题的话，那别的固件又能用，也能正常刷写。电源，，这个难道这个固件比其他的固件电压要高点？？

**Comment by garypang13** [comment]
是的,这个固件有默认超频,如果不是随r2s一起而是自己配的电源的话,可能会电压不够,

**Comment by iii6** [comment]
@garypang13 那现在有没有办法把网口换回来？我自己去编译一份看看

**Comment by garypang13** [comment]
https://github.com/garypang13/Actions-OpenWrt/blob/9bcd7eebd2fa35f262fa5c7ac89435c1da61e56b/devices/nanopi-r2s/diy.sh#L7

**Comment by iii6** [comment]
@garypang13 好的，谢谢。我去试试
