### ISSUE TITLE
k2p iptables-mod-filter插件安装不上

### ISSUE THREAD

**Issue by qq1907** [kiddin9/OpenWrt_x86-r2s-r4s#204]
错误
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ipt-filter found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for iptables-mod-filter:
 * 	kernel (= 5.4.80-1-d8f1aa646eb2674fdadccb6f6c3309d0)
 * opkg_install_cmd: Cannot install package iptables-mod-filter.

**Comment by garypang13** [comment]
下一版修复.
