### ISSUE TITLE
部分网站无法访问

### ISSUE THREAD

**Issue by helloworldandcode** [kiddin9/OpenWrt_x86-r2s-r4s#241]
FriendlyElec NanoPi R2S
OpenWrt SNAPSHOT 12.28.2020 by GaryPang / LuCI Master git-6ffd159
你好，我在使用的过程中发现一个问题一直都没有找到解决方法。在不用软路由来代理而是在自己的电脑上代理时，不接openwrt所有的都能正常访问，接了这个固件的r2s后，油管，gmail正常但是Google主页和学术就是上不去。在dhcp/dns里改了好久还是这样，希望能解答，是有什么规则我没看到吗？谢谢

**Comment by duxiangjiang** [comment]
你在路由器上是用gfw-list模式还是国外ip模式，我早年在路由器上设代理也是油管正常，google无法访问，后来发现是我用了gfw-list模式，由于代理服务器在香港，访问google时会自动转到google.com.hk这个域名，而这个域名并不在gfw-list中，后来是自己手动把这个域名加进去解决的，你可以看看是否是我当时相同的原因。
