### ISSUE TITLE
无法自定义DNS

### ISSUE THREAD

**Issue by coLATin** [kiddin9/OpenWrt_x86-r2s-r4s#242]
bypass插件DNS全部通过smartdns，而固件又没有提供smartdns，搞不懂。
另外翻墙插件即便单指向smartdns也不太人性化，我就习惯用adg。

**Comment by garypang13** [comment]
@coLATin smartdns是bypass的一个默认依赖,是由bypass来控制的,并没有提供另外的管理页面,bypass的特色就是无脑开箱即用,如果想折腾建议使用passwall,
