### ISSUE TITLE
luci-app-nlbwmon安装并重启后设备启动失败

### ISSUE THREAD

**Issue by fhleo** [kiddin9/OpenWrt_x86-r2s-r4s#245]
设备类型：X86(虚拟机)
版本：2021.01.03
问题现象：成功安装luci-app-nlbwmon并重启后设备一致反发重启，无法进入系统。
操作步骤：
系统—>软件包—>过滤器—>luci-app-nlbwmon—>安装—>完成安装后控制台（SSH）输入reboot

**Comment by garypang13** [comment]
@fhleo 感谢反馈,  下版修复,

**Comment by littlewhitelyw** [comment]
哇，这个包太坑了。。。两次路由器无限重启都不知道是什么原因，又试了一下这个包，果然又崩了
红米AC2100，20210112

**Comment by garypang13** [comment]
已修复,更新软件列表后重新安装luci-app-nlbwmon即可.
