### ISSUE TITLE
X86:ppp-mod-pppol2tp无法安装

### ISSUE THREAD

**Issue by fhleo** [kiddin9/OpenWrt_x86-r2s-r4s#246]
提示：
已安装的软件包 kernel 版本不兼容，要求 5.4.86-1-1cc178c1… 而 5.4.85-1-470d3e14… 已安装。
报错信息：
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-l2tp found, but incompatible with the architectures configured
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-pppol2tp found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for ppp-mod-pppol2tp:
 * 	kernel (= 5.4.86-1-1cc178c1f8d6c85a5513a864a5d45c6e)
 * opkg_install_cmd: Cannot install package ppp-mod-pppol2tp.

**Comment by garypang13** [comment]
ppp l2tp 都属于淘汰的技术了,别用了,

**Comment by fhleo** [comment]
请问目前 L2TP 客户端应该使用什么哪个包

**Comment by garypang13** [comment]
@fhleo xl2tpd l2tpd 下一版支持.
