### ISSUE TITLE
可以跟新支持R4S吗？

### ISSUE THREAD

**Issue by flywbo** [kiddin9/OpenWrt_x86-r2s-r4s#249]
这个固件算是我用的最方便好用的openwrt了

**Comment by garypang13** [comment]
R4S再看看,目前用的人太少了,

**Comment by garypang13** [comment]
https://op.supes.top/firmware/nanopi-r4s/  已支持.

**Comment by Whozki** [comment]
> https://op.supes.top/firmware/nanopi-r4s/ 已支持.

大佬，传错了，你上传成R2S的固件了

**Comment by garypang13** [comment]
已重新上传.
