### ISSUE TITLE
系统更新后zerotier node id改变

### ISSUE THREAD

**Issue by Omoinemie** [kiddin9/OpenWrt_x86-r2s-r4s#252]
系统更新后node id改变，会导致zerotier掉线，需要去官网后台重新设置允许

**Comment by garypang13** [comment]
node id是自动生成的么,是的话那没办法,只能尽量别更新固件了,

**Comment by Omoinemie** [comment]
系统是x86，可能固件包里面包含的UUID每次都在变，能不能固定下来
