### ISSUE TITLE
是否可以在群晖 通过VMM安装此固件

### ISSUE THREAD

**Issue by ideatechfr** [kiddin9/OpenWrt_x86-r2s-r4s#254]
在K2P上已经用这个固件一段时间，感觉系统稳定，满足基本网络业务管理。打算在群晖上通过VMM安装这个固件，不知大佬我们哪个版本适合在VMM上安装？
感谢！

**Comment by garypang13** [comment]
x86_64  https://op.supes.top/firmware/x86_64/

**Comment by ideatechfr** [comment]
收到！麻烦问一下应该下载 openwrt-x86-64-generic-squashfs-combined-efi.img.gz 还是 openwrt-x86-64-generic-squashfs-combined.img.gz ？是否有vmdk格式的
