### ISSUE TITLE
可以编译一个docker版吗

### ISSUE THREAD

**Issue by yepochangfeng** [kiddin9/OpenWrt_x86-r2s-r4s#257]
如题，可以帮忙编译一个docker版吗，自己编译老是报错，不知道是不是没挂梯子的缘故

**Comment by garypang13** [comment]
需要docker的话在后台 软件包 中在线安装dockerman即可.

**Comment by yepochangfeng** [comment]
> 需要docker的话在后台 软件包 中在线安装dockerman即可.

装了dockerman还是没有docker信息，像docker版本啥的都显示--，ssh登录过去运行docker命令也是报无法识别命令，所以我想着是不是docker没编译进去，我的设备是r2s。

**Comment by garypang13** [comment]
docker版本啥的都显示还是都不显示?

**Comment by yepochangfeng** [comment]
> docker版本啥的都显示还是都不显示?

都不显示

**Comment by garypang13** [comment]
@yepochangfeng dockerd 装了吗

**Comment by yepochangfeng** [comment]
装了，现在设备没在手头，回头我把截图放上来吧
