### ISSUE TITLE
nanooi r4s

### ISSUE THREAD

**Issue by wifiway520** [kiddin9/OpenWrt_x86-r2s-r4s#261]
感谢大佬编译和插件支持，15点时还可以进入网盘下载，15.36显示404了。自己编译或多或少总是有问题，而且自己也没解决的能力，还是请大佬维护下，再次感谢大佬！
另外，请问下大佬，我看了官方默认存储是160M，不知道r4s默认是多大空间！

**Comment by garypang13** [comment]
已重新上架,我设置默认是1G.

**Comment by wifiway520** [comment]
感谢大佬，还请问譬如usb2.usb3接口驱动(不是外接设备驱动)，还有分区、格式化这些命令直接自带还是要后台安装。



---Original---

**Comment by garypang13** [comment]
usb驱动有自带, 分区、格式化这些命令要自己安装对应的插件包
