### ISSUE TITLE
请教一下，这些依赖包怎么没了？

### ISSUE THREAD

**Issue by lzqd** [kiddin9/OpenWrt_x86-r2s-r4s#263]
请教一下，这些依赖包怎么没了？
![QQ截图20210118203010](https://user-images.githubusercontent.com/68813588/104915844-3017d200-59cc-11eb-989e-671c7ff42ee0.png)

**Comment by lzqd** [comment]
![QQ截图20210118203010](https://user-images.githubusercontent.com/68813588/104915900-4160de80-59cc-11eb-8237-4740ef12a911.png)

**Comment by garypang13** [comment]
可能是显示问题,不用管,直接点安装.
