### ISSUE TITLE
如何同步整个插件仓库？

### ISSUE THREAD

**Issue by hmsjy2017** [kiddin9/OpenWrt_x86-r2s-r4s#266]
是否支持rsync协议？
考虑添加到上海交大镜像源

**Comment by garypang13** [comment]
你这边有权限添加到上海交大镜像源么,

**Comment by hmsjy2017** [comment]
> 你这边有权限添加到上海交大镜像源么,

有请求新镜像的权利，同意之后就能添加进去。
比如我提交的 Linux Lite 就给添加进去了

**Comment by hmsjy2017** [comment]
如果不提供 rsync 的话同步会比较麻烦。[#151](https://github.com/sjtug/mirror-requests/issues/151)

**Comment by garypang13** [comment]
已支持rsync
rsync://op.supes.top/packages

**Comment by skyzh** [comment]
感谢各位的支持。不过我想确认一下，这个源是否存在潜在的版权问题？

**Comment by skyzh** [comment]
刚刚发现有类似 https://op.supes.top/packages/x86_64/vlmcsd_svn1113-1_x86_64.ipk 的内容，我们评估下来镜像这个源的风险比较大，所以可能会暂时搁置镜像的计划。
