### ISSUE TITLE
添加树莓派 4B 支持

### ISSUE THREAD

**Issue by hmsjy2017** [kiddin9/OpenWrt_x86-r2s-r4s#277]
树莓派 4B 性能较强，可玩性高，以太网跑满千兆，支持 USB 3.0，内存（RAM）最高可达 8GB。价格也不贵。

**Comment by garypang13** [comment]
树莓派和r2s,r4s所用的软件架构不一样,还得单独维护一个软件源,考虑到用的人实在太少,还是算了.
