### ISSUE TITLE
软件源镜像

### ISSUE THREAD

**Issue by hmsjy2017** [kiddin9/OpenWrt_x86-r2s-r4s#278]
https://github.com/hmsjy2017/openwrt-packages
每天早上5点自动同步

**Comment by garypang13** [comment]
谢谢.

**Comment by hmsjy2017** [comment]
https://iamsjy.coding.net/p/packages/d/openwrt-packages/git/raw/main/
国内推荐使用 Coding 源

**Comment by hmsjy2017** [comment]
@garypang13 仓库太大，Coding无法同步。现每天自动同步到 OSDN ，可以通过 Tsinghua、BFSU 的镜像加速访问。提高软件包下载速度，缓解 op.supes.top 主服务器压力。
OSDN：https://osdn.net/projects/openwrt-packages/
Tsinghua：https://mirrors.tuna.tsinghua.edu.cn/osdn/storage/g/o/op/openwrt-packages/
BFSU：https://mirrors.bfsu.edu.cn/osdn/storage/g/o/op/openwrt-packages/
