### ISSUE TITLE
snmpd插件安装后无效

### ISSUE THREAD

**Issue by solodarker** [kiddin9/OpenWrt_x86-r2s-r4s#280]
爱快X86虚拟机下跑的op
op安装snmpd插件提示为最新。
爱快开启跨三层应用，一直异常，op的snmpd没工作？

**Comment by garypang13** [comment]
命令行执行 
uci set snmpd.general.enabled="1"
uci commit snmpd

**Comment by jiezuowhu** [comment]
> 命令行执行
> uci set snmpd.general.enabled="1"
> uci commit snmpd

执行完重启一下，就好啦
