### ISSUE TITLE
这个samba3.X的版本没有Ui吗？

### ISSUE THREAD

**Issue by lzqd** [kiddin9/OpenWrt_x86-r2s-r4s#295]
这个samba3.X的版本没有Ui吗
samb4的就有ui

**Comment by garypang13** [comment]
samba3.X请用ksmbd替代,

**Comment by lzqd** [comment]
> samba3.X请用ksmbd替代，

这个ui使用的版本和中文包的版本不一致是什么情况### 
![QQ截图20210208143830](https://user-images.githubusercontent.com/68813588/107184445-8dc39b00-6a1b-11eb-8d13-0d204e1419ff.png)
![QQ截图20210208143743](https://user-images.githubusercontent.com/68813588/107184463-94521280-6a1b-11eb-9441-d7e2e4f73a1d.png)

**Comment by lzqd** [comment]
> samba3.X请用ksmbd替代,

samba4也存在ui和语言包版本不匹配，然后语言包问题导致汉化无法使用

**Comment by garypang13** [comment]
1. 确实是否有安装对应的语言包
2. ctrl+F5 刷新浏览器缓存

**Comment by lzqd** [comment]
![QQ截图20210319002522](https://user-images.githubusercontent.com/68813588/111661059-a9effe80-8849-11eb-8ef2-27f1b6ba3b45.png)
![QQ截图20210319002531](https://user-images.githubusercontent.com/68813588/111661071-aceaef00-8849-11eb-8c96-1fe357ece4bd.png)
UI和翻译版本还是不一致，为什么会这样？
