### ISSUE TITLE
Newifi-D2 (新路由3)opkg相关问题

### ISSUE THREAD

**Issue by Top20000316** [kiddin9/OpenWrt_x86-r2s-r4s#299]
无法执行 opkg update 和opkg install 命令，提示SyntaxError: Unexpected end of JSON input
请问应该如何解决？

**Comment by shyperwang** [comment]
我也有这个问题

**Comment by Top20000316** [comment]
> 我也有这个问题

如果找到解决方法方便的话请说一下 谢谢

**Comment by shyperwang** [comment]
> > 我也有这个问题
> 
> 如果找到解决方法方便的话请说一下 谢谢

他编译的配置文件有问题，你用他2.17的就不会有这个问题了，不过配置文件里的地址不存才会提示升级包下载错误。最好刷完后添加其他的软件包源

**Comment by garypang13** [comment]
固件有更新, 刷最新版

**Comment by Top20000316** [comment]
> 固件有更新, 刷最新版

感谢！
