### ISSUE TITLE
r4s 我家动态ip7天换一次。7天后强制下线，但是不自动重播或者重播无法上网，需手动连接才行

### ISSUE THREAD

**Issue by 331969102** [kiddin9/OpenWrt_x86-r2s-r4s#304]
r4s 我家动态ip7天换一次。7天后强制下线，但是不自动重播或者重播无法上网，需手动连接才行。

**Comment by avsba001** [comment]
0 4 */3 * * ifup wan
计划任务里面加这个试试，

**Comment by 331969102** [comment]
> 0 4 */3 * * ifup wan
> 计划任务里面加这个试试，

请问这串的代码是什么 意思？

**Comment by Tiexcn** [comment]
> > 0 4 */3 * * ifup wan
> > 计划任务里面加这个试试，
> 
> 请问这串的代码是什么 意思？

固定某个时间，判断外网IP是否更新。
