### ISSUE TITLE
device 怎么配置？请教大神

### ISSUE THREAD

**Issue by mocl1220** [kiddin9/OpenWrt_x86-r2s-r4s#308]
大神们，尝试了多次自己自制device，都编译失败，请问怎么定义里面的.config和patchs，好像有的不用patch也可以，.config如果把自己生成的直接放进去总是出错，是不是和common里的.config有冲突？ 精简后只剩下基本的配置也不成功，比如我想制作mt7628  hiwifi hc5661a， 该怎么定义呢？

**Comment by lon91ong** [comment]
我是查找同硬件配置的已有路由器的文件直接复制在略加改动，比如，参考youku-l2的配置编译应该SPI闪存的hiwifi-hc5962
