### ISSUE TITLE
koolproxy3.8.4版本https证书过期。

### ISSUE THREAD

**Issue by lovedreamland** [kiddin9/OpenWrt_x86-r2s-r4s#310]
3.8.5版本已经修复证书过期的问题，建议更新一下。

**Comment by garypang13** [comment]
哪里有3.8.5

**Comment by lovedreamland** [comment]
> 哪里有3.8.5

这里
https://www.right.com.cn/forum/thread-4064914-1-1.html

**Comment by garypang13** [comment]
没找到github源码,

**Comment by duxiangjiang** [comment]
> 没找到github源码,

https://github.com/tofuliang/luci-app-koolproxyR
这个应该是3.8.5的，希望大大编译一下，整合进软件仓库

**Comment by lovedreamland** [comment]
> 没找到github源码,

我试了直接替换koolproxy主程序就可以，其他不用改。

**Comment by uminoai** [comment]
> > 没找到github源码,
> 
> 我试了直接替换koolproxy主程序就可以，其他不用改。

求问具体怎么替换呀，求教
