### ISSUE TITLE
更新后动态DNS腾讯云dnspod无法运行

### ISSUE THREAD

**Issue by Omoinemie** [kiddin9/OpenWrt_x86-r2s-r4s#312]
版本：02.19.2021
故障：dnspod.cn ipv4和ipv6解析均无法运行，重启也不行

**Comment by HalcyonAzure** [comment]
dyvn6的ddns服务在之前的版本有类似问题，设备R2S，更新到3.3的固件之后就能恢复使用了，可以更新试试看
