### ISSUE TITLE
XHR request timed out

### ISSUE THREAD

**Issue by gLoCk27** [kiddin9/OpenWrt_x86-r2s-r4s#322]
#主机名 | OpenWrt
#型号 | FriendlyElec NanoPi R2S (CpuMark : 15045.692743 Scores)
#固件版本 | OpenWrt SNAPSHOT 03.03.2021 by GaryPang / LuCI Master git-7057108

运行时间稍长，一般是>1天之后
进10.0.0.1页面会很慢，
大概率出现红色字体 XHR request timed out
再刷新页面就 Bad request
无法再访问
只能断电重启恢复
但是上网什么的不受影响
只是这个页面挂掉了

**Comment by aweiu** [comment]
这个问题我也遇到了，重刷也没用。
只能输入其他路径绕过首页。然后 passwall 也启动不了，等待好久提示应用成功后会注销登录，再进去后发现开关并没有打开。
反正现在的症状就是：
1. 进首页就会卡住然后触发重启
2. passwall 应用不了

**Comment by striver8** [comment]
我也遇到了，会突然没网，网络超级慢，访问管理页面进不去，想上传固件也都是xhr time out
