### ISSUE TITLE
luci-app-openvpn-server无法生成证书

### ISSUE THREAD

**Issue by IveanEx** [kiddin9/OpenWrt_x86-r2s-r4s#328]
我的路由器是红米AC2100，大概从一个月前开始luci-app-openvpn-server就无法生成证书了，不管直接点Web页面的生成证书还是执行脚本好像都没效果……

**Comment by huanglin199009** [comment]
我的也是这样，求解决方法

**Comment by huanglin199009** [comment]
openvpn: OpenVPN 2.5.5 mipsel-openwrt-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]

**Comment by huanglin199009** [comment]
NOTE: the current --script-security setting may allow this configuration to call user-defined scripts

**Comment by huanglin199009** [comment]
OpenSSL: error:02001002:system library:fopen:No such file or directory

**Comment by huanglin199009** [comment]
OpenSSL: error:2006D080:BIO routines:BIO_new_file:no such file

**Comment by huanglin199009** [comment]
NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.

**Comment by huanglin199009** [comment]
NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
