### ISSUE TITLE
装不上京东签到插件

### ISSUE THREAD

**Issue by KrisCris** [kiddin9/OpenWrt_x86-r2s-r4s#334]
<img width="708" alt="截屏2021-03-26 上午3 24 30" src="https://user-images.githubusercontent.com/38860226/112531779-efc93b80-8de2-11eb-9b74-93ec1009e0c0.png">
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-jd-dailybonus found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-jd-dailybonus.

**Comment by yearqp** [comment]
打开https://op.supes.top/packages获得你路由器处理器对应架构名，将该名字换掉/etc/opkg/distfeeds.conf 内src/gz openwrt_custom https://op.supes.top/packages/后面的字符

**Comment by yearqp** [comment]
除此之外你还需要得到node的安装包，可以通过网络资源（如https://openwrt.download/)或自行编译获得

**Comment by KrisCris** [comment]
ok，过两天我试试去
