### ISSUE TITLE
PVE虚拟机X86版cpu占用奇高

### ISSUE THREAD

**Issue by coLATin** [kiddin9/OpenWrt_x86-r2s-r4s#342]
![image](https://user-images.githubusercontent.com/749762/113293717-b3d52f80-9328-11eb-96b5-c76bf5e2dc1d.png)

这可是T9900的U啊，首先显示不正确，另外cpu占用奇高，之前貌似5%的时候都不多，现在始终在30-40%。。。。

**Comment by garypang13** [comment]
命令行 htop 查看时哪些进程占用的CPU

CPU显示不正确时因为用了PVE,显示的就是虚拟出来的CPU信息.

**Comment by coLATin** [comment]
![image](https://user-images.githubusercontent.com/749762/113295106-593cd300-932a-11eb-9939-fda82c083f37.png)

**Comment by coLATin** [comment]
用工具按照cpu从高到底捋，也并没有过分的占用....奇怪了

**Comment by coLATin** [comment]
![image](https://user-images.githubusercontent.com/749762/113295679-16c7c600-932b-11eb-9feb-2da59af0c5d4.png)
并且是持续的，内存也吃了2g多.....

**Comment by coLATin** [comment]
![image](https://user-images.githubusercontent.com/749762/113297384-1fb99700-932d-11eb-8337-a0cc76987de9.png)
bypass的插件是主要原因，杀进程后25%（也是高），启用bypass进程后，就一直在40%多了

**Comment by 283915025** [comment]
虚拟机CPU选host，不然效率太低
