### ISSUE TITLE
老板能增加个切换19.07版本的功能吗？

### ISSUE THREAD

**Issue by uray2020** [kiddin9/OpenWrt_x86-r2s-r4s#345]
21.02太新了，用下来不是太稳定，lean版本的upnp和转发问题太多
能不能编译流程上增加个指定19.07的stalbe分支的功能
就是想在官方19.07稳定版本上加上基础补丁和翻墙插件而已，感谢。

**Comment by lon91ong** [comment]
+1

**Comment by yhl452493373** [comment]
估计不会加。。。19的和20的代码差异，又得一个一个补丁

**Comment by harion2yyy** [comment]
+1，21.02太新了，r4s现在没有node，JD签到的插件都装不了

**Comment by lon91ong** [comment]
给斐讯k2折腾了一个[使用bypass的lede-17.01分支版固件](https://github.com/lon91ong/Actions-OpenWrt/tree/bypass), 可以参考一下自己改
