### ISSUE TITLE
Qos over Nftables 功能没有生效

### ISSUE THREAD

**Issue by ideatechfr** [kiddin9/OpenWrt_x86-r2s-r4s#350]
x86 系统，版本升级到OpenWrt 21.02-SNAPSHOT 04.03.2021 ，因为用户比较多，所以配置了Qos over Nftables功能
![屏幕快照 2021-04-08 下午5 48 04](https://user-images.githubusercontent.com/37808758/114057549-ee901800-9892-11eb-8091-09de36afdd8f.png)
应用后，实测客户端的速度没有被限制。

另外，在状态里实时信息，里面有个实时速率显示，我链接了3个终端进行网速测试，但这里没有显示，能不能帮忙看一下什么问题
![屏幕快照 2021-04-08 下午5 51 21](https://user-images.githubusercontent.com/37808758/114057880-44fd5680-9893-11eb-8209-8c384adb34b3.png)

**Comment by garypang13** [comment]
关闭 turbo acc网络加速中的 Shortcut-FE 流量分载 后再试试.

**Comment by ideatechfr** [comment]
已经关了，限速还是没有生效

![屏幕快照 2021-04-08 下午5 56 25](https://user-images.githubusercontent.com/37808758/114058478-c3f28f00-9893-11eb-95ca-48d626633df0.png)

**Comment by garypang13** [comment]
![image](https://user-images.githubusercontent.com/48883331/114059141-a68ae880-98c6-11eb-9087-7376dab50ca7.png)

**Comment by ideatechfr** [comment]
设置为静态地址过滤
![截屏2021-04-08 18 04 43](https://user-images.githubusercontent.com/37808758/114059953-3021c280-9895-11eb-957d-dc59a72f46f3.png)
实测网速
![截屏2021-04-08 18 04 57](https://user-images.githubusercontent.com/37808758/114060031-429bfc00-9895-11eb-8ea4-eb15e536fd4a.png)

**Comment by garypang13** [comment]
确实有问题,等我后续再做测试和修复.

**Comment by ideatechfr** [comment]
好的，谢谢！

另外还发现Rate实时速率显示功能，里面的IP不是唯一，有很多重复IP显示在列表里。因为现在测试是只有10多个IP链接，但列表已经拉的很长。 麻烦帮忙看看是否可以解决
![截屏2021-04-09 下午2 43 27](https://user-images.githubusercontent.com/37808758/114181619-05417800-9942-11eb-9e70-cd54f9854d64.png)

**Comment by iwrt** [comment]
nft确实没有用
