### ISSUE TITLE
可以自行安装主题吗？

### ISSUE THREAD

**Issue by wangzan200808** [kiddin9/OpenWrt_x86-r2s-r4s#362]
下载了一个主题，安装之后再系统修改主题界面并没有出现，是禁用了主题安装吗？

**Comment by garypang13** [comment]
什么设备,固件版本号是多少,

**Comment by wangzan200808** [comment]
newifi3 D2 版本号是这个吗？

OpenWrt SNAPSHOT 04.11.2021 by GaryPang / LuCI openwrt-21.02 branch git-3fff72a
