### ISSUE TITLE
更新后丢失软件包和配置

### ISSUE THREAD

**Issue by CoolZxp** [kiddin9/OpenWrt_x86-r2s-r4s#363]
通过PVE安装的X86-64版的，但是每次通过系统内的更新都会恢复初始设置，包括密码什么的

**Comment by 33625894** [comment]
是的  备份的配置 也不能恢复   说是什么指定错误

**Comment by dsyo2008** [comment]
同样，刚才更新后变成初始设置，我郁闷，我不容易设置大量，以后不敢点更新，只更新软件包就行
