### ISSUE TITLE
京东安装错误

### ISSUE THREAD

**Issue by 33625894** [kiddin9/OpenWrt_x86-r2s-r4s#364]
![image](https://user-images.githubusercontent.com/82663651/115037829-77492c80-9f01-11eb-891e-2f4cd8adff68.png)
![W@LH TH)C@)NXT528E8~WB9](https://user-images.githubusercontent.com/82663651/115037856-816b2b00-9f01-11eb-9fe0-a6a6830492c3.png)

**Comment by windy9275** [comment]
同样的问题，提示架构不匹配
