### ISSUE TITLE
K2P新版无线速度非常差

### ISSUE THREAD

**Issue by TXH201622** [kiddin9/OpenWrt_x86-r2s-r4s#367]
自从换了开源驱动后，穿墙后无线速度严重下降，而且打游戏很不稳定。能否换回原来的闭源驱动？

**Comment by michaelsara** [comment]
同样遇到过，其他旧版本其他系列openwrt，网络测试可以打到带宽上限，但是使用5月26日版本，下载测试只有25Mbps左右，而实际带宽为300Mbps，麻烦大佬看能不能换下驱动，感谢
