### ISSUE TITLE
设备小米路由AC2100

### ISSUE THREAD

**Issue by 0x2CA** [kiddin9/OpenWrt_x86-r2s-r4s#371]
我拥有着小米路由AC2100,我非常喜欢你的集成，但是我看只有红米路由AC2100，当然据我所致外壳不一样，内部配置是一样的，通常是可以混用固件，当然现在我就是这样做的，并且非常完美的运行着，有点遗憾是设备型号不正确，因为固件并不是我这个设备的，我想了解有什么特别注意的嘛，或者你如果可以适配一下我非常高兴的

**Comment by Magic-Xin** [comment]
AC2100 和 RM2100 可以通刷，可能会出现有个 LAN 口不能用的情况，自己试试就好了
