### ISSUE TITLE
红米ac2100四月26号驱动更改！？

### ISSUE THREAD

**Issue by Tinnci** [kiddin9/OpenWrt_x86-r2s-r4s#374]
红米ac2100四月26号更改为**_闭源驱动_**导致**无线设置错误**，**只能初始化**openwrt。
玛德ipv6 nat adguard**配置都没了**，**更新内容里面毫无提及****？！！**

**Comment by loy23333aI** [comment]
也不对啊，但是显示的的确是闭源驱动，重刷了不保留配置也没用，好奇怪。。。
