### ISSUE TITLE
小米ac2100。

### ISSUE THREAD

**Issue by 2398131119** [kiddin9/OpenWrt_x86-r2s-r4s#377]
你好，我非常喜欢用你的固件。一直都有更新。
我发现最近的固件好像会出现5gWiFi断开连接.过几秒后又会恢复。出现的非常频繁。
大佬。指点一下设置方法或快修复。辛苦了谢谢！

**Comment by garypang13** [comment]
是更新到5月份的最新固件才出现的问题么, 尝试关闭 Turbo ACC 网络加速中的 natflow加速 试试,

**Comment by 2398131119** [comment]
> 是更新到5月份的最新固件才出现的问题么，尝试关闭Turbo ACC网络加速中的natflow加速尝试，

呃，你好，里面有一个全锥形 NAT.我现在关闭试试。如果不是这个麻烦指点。

**Comment by 2398131119** [comment]
> 你目前用的固件的版本号是多少,
> 上一个没有这个问题的版本号是多少,
> 我得确定是从哪个版本开始出现的问题.

目前的是115.什么时候出现的没有注意，好像是4月下旬。5月初开始差不多。
