### ISSUE TITLE
wireguard无法安装提示内核版本过低

### ISSUE THREAD

**Issue by a350147909** [kiddin9/OpenWrt_x86-r2s-r4s#385]
需要kernel 5.4.120及以上

**Comment by garypang13** [comment]
什么路由器

**Comment by a350147909** [comment]
k2p

**Comment by messense** [comment]
想试试这个固件来着，也需要 wireguard，可以增加预编译下？

**Comment by kiddin9** [comment]
正常安装.

**Comment by messense** [comment]
试了下直接安装 luci-app-wireguard，安装成功没有报错

![image](https://user-images.githubusercontent.com/1556054/132938407-8df0c90a-7884-48ff-bb5d-9fd20b7f593f.png)

但是无法添加新的 wireguard 接口，没有对应的选项

![image](https://user-images.githubusercontent.com/1556054/132938413-c74db82e-f92d-4669-be5c-9410d8cf514e.png)

**Comment by kiddin9** [comment]
要重启下路由器

**Comment by messense** [comment]
重启后可以了，感谢！

BTW，感觉浏览器打开 op/ 后台很慢，登录进去之后就好了。

**Comment by kiddin9** [comment]
> 重启后可以了，感谢！
> 
> BTW，感觉浏览器打开 op/ 后台很慢，登录进去之后就好了。#411

后台慢的问题已修复,可秒开, 更新到最新固件即可.
