### ISSUE TITLE
unblockmusic-Golang 修复后还是报错

### ISSUE THREAD

**Issue by STGGxd** [kiddin9/OpenWrt_x86-r2s-r4s#405]
/usr/lib/lua/luci/cbi.lua:53：找不到模型“unblockmusic”！
堆栈回溯：
[C]：在函数'assert'中
/usr/lib/lua/luci/cbi.lua:53：在函数'load'中
/usr/lib/lua/luci/dispatcher.lua:1353：在函数'中_cbi'
/usr/lib/lua/luci/dispatcher.lua:1024: 在函数 'dispatch'
/usr/lib/lua/luci/dispatcher.lua:985: 在函数 'dispatch'
/usr/lib/lua/luci /dispatcher.lua:479: 在函数中 </usr/lib/lua/luci/dispatcher.lua:478>

**Comment by garypang13** [comment]
@STGGxd 什么设备,有卸载重装吗

**Comment by STGGxd** [comment]
> @STGGxd 什么设备,有卸载重装吗
k2p a2
有重装过多次 
系统版本是6.2号发布的

**Comment by garypang13** [comment]
@STGGxd 是 luci-app-unblockmusic 这个吗, 这个我确定是已经修复了.

**Comment by STGGxd** [comment]
> @STGGxd 是 luci-app-unblockmusic 这个吗, 这个我确定是已经修复了.

我安装了这两个插件UnblockNetaseMusic-Go  ； luci-app-unblockmusic ；
打开显示报错
