### ISSUE TITLE
刚才软路由在线升级了最新系统，结果不能登录openwrt了

### ISSUE THREAD

**Issue by talentzzd** [kiddin9/OpenWrt_x86-r2s-r4s#406]
刚才软路由在线升级了最新系统，结果不能登录openwrt了，后台vi /etc/config/network查看ip地址还是192.168.1.1，但是虚拟机后台显示的是这样的，什么原因呢
![IMG_9038(20210607-210327)](https://user-images.githubusercontent.com/49876748/121021356-e17ca000-c7d3-11eb-97fa-d7be0bc32f0b.JPG)

**Comment by avsba001** [comment]
nano /etc/config/network  把brige那行去掉，然后只保留一个网口就可以进后台了，不知道是上游问题还是编译问题，不能桥接多网口了

**Comment by avsba001** [comment]
> nano /etc/config/network 把brige那行去掉，然后只保留一个网口就可以进后台了，不知道是上游问题还是编译问题，不能桥接多网口了

更新下，这是因为6.3日版本lan口信息变动，需要手动建一个lan桥接端口
