### ISSUE TITLE
docker和adbyby plus的问题

### ISSUE THREAD

**Issue by znw0917** [kiddin9/OpenWrt_x86-r2s-r4s#408]
这个固件整体感觉很好，可以自己定制安装，我非常喜欢。
1、希望改进的，我是2G内存，系统空间全部1.45G，可用估计由300多兆吧，docker安装后，什么都下载不了，等于没装，而docker是我最喜欢的一个插件。我可以进pe进行扩展分区，但是看网上说会影响升级，所以就没搞。但是这个用着非常不爽。不知道有没有方法，我来帮你们写代码也行啊。
2、安装了adbyby plus，但是选项都是英文的，我去找118的对应包没找到，可能我是openwrt新手，确实不知道咋弄。烦请帮忙。

**Comment by garypang13** [comment]
https://tinyurl.com/yzkzm3yq 按照这个教程创建和挂载新分区,不影响升级,

**Comment by znw0917** [comment]
按照上述教程，成功配置了docker空间，容器也运行起来了，更新新版6.12以后，docker不见了。。。。diskman也没了，好不容易配置好的docker有办法找回没

**Comment by garypang13** [comment]
dockerman和diskman在更新完系统后等一会会自动安装上的,如果没自动安装上,手动去软件包中安装下,所有配置都不会丢失.

**Comment by znw0917** [comment]
可能我等的时间不够，没有自动安装，我手动安装的，东西都在，挂载好以后容器都在，不错

**Comment by flyingzl** [comment]
我的 docker 、 diskman 、 openclash 等插件也都是全部丢失了。 @kiddin9
