### ISSUE TITLE
还没几天，K2p，AC2100全没了？

### ISSUE THREAD

**Issue by brightsm** [kiddin9/OpenWrt_x86-r2s-r4s#409]

**Comment by wangxian** [comment]
我的也是 AC2100 路由器，正在使用，以后不能升级了吗？

**Comment by avsba001** [comment]
小存储的都删了

**Comment by wangxian** [comment]
redmi ac 2100 2021/6/12 日的固件，升级后原有插件需要手工安装，重新安装插件重启后，不能正常进入openwrt 系统。

固件：06.12-openwrt-ramips-mt7621-redmi-ac2100-squashfs-sysupgrade.bin

插件：
- luci-i18n-ddns
- luci-app-nlbwmon

不兼容，请大家谨慎升级

**Comment by brightsm** [comment]
6月份版本确实有点问题，月初刷 了6月版本，中继功能不好，现在使用的是4月份版本。中继正常。



在 2021-06-15 16:48:52，"wangxian" ***@***.***> 写道：

redmi ac 2100 2021/6/12 日的固件，升级后原有插件需要手工安装，重新安装插件重启后，不能正常进入openwrt 系统。

固件：06.12-openwrt-ramips-mt7621-redmi-ac2100-squashfs-sysupgrade.bin

插件：

luci-i18n-ddns
luci-app-nlbwmon

不兼容，请大家谨慎升级

**Comment by ssrubsd** [comment]
应该说是停止更新了
