### ISSUE TITLE
那路由器登录时动态背景太卡了，能不改静态吗？

### ISSUE THREAD

**Issue by dsyo2008** [kiddin9/OpenWrt_x86-r2s-r4s#411]
因为我远程，发现这动态背景太卡了，导致打开太慢。只能换其他主题，但其他主题不好看。希望有主题设置就好，也改静态背景就行。

**Comment by znw0917** [comment]
我也觉得这个没撒必要，还有声音吓我一跳

**Comment by yhl452493373** [comment]
你装argon主题呗，和这个差不多

**Comment by znw0917** [comment]
> 你装argon主题呗，和这个差不多

直接用了bootstrap
