### ISSUE TITLE
如何修改ROOT账号

### ISSUE THREAD

**Issue by eming36881** [kiddin9/OpenWrt_x86-r2s-r4s#412]
想把ROOT用户名修改成自己所需要的用户名，如何操作？

**Comment by BirtyAs** [comment]
**！ 可能会造成严重后果**
**！ 可能会造成严重后果**
**！ 可能会造成严重后果**

vi /etc/passwd
按i键进入编辑状态
修改第1行第1个root为新的用户名
按esc键退出编辑状态，并输入:x保存并退出
vi /etc/shadow
按i键进入编辑状态
修改第1行第1个root为新的用户名
按esc键退出编辑状态，并输入:x!强制保存并退出
