### ISSUE TITLE
adguardhome无法删除

### ISSUE THREAD

**Issue by znw0917** [kiddin9/OpenWrt_x86-r2s-r4s#416]
在软件包管理里面，删除adguardhome后，在服务里看不到了，过一阵子又在服务里出现，无法真正删除，怎么彻底删除啊？

**Comment by garypang13** [comment]
删除 luci-app-adguardhome 和对应的语言包

**Comment by znw0917** [comment]
> 删除 luci-app-adguardhome 和对应的语言包

就是在软件包已安装里面做的移除，服务里也不显示了。过一阵子刷新openwrt又在服务菜单下

**Comment by znw0917** [comment]
实在不行，我就重刷了
