### ISSUE TITLE
R2S P4 都刷了，但系统无法运行请教

### ISSUE THREAD

**Issue by OoNanGeOo** [kiddin9/OpenWrt_x86-r2s-r4s#424]
内存卡都能识别没问题，R2S和P4都是用Win32DiskImager写的系统，都下载到了各个版本7.2，用1988 骷髅头等都没问题，唯独刷了大佬的系统不识别无法启动，是我工具用错了吗？

**Comment by lengyuqu** [comment]
同样的问题，最新的版本启动不了
