### ISSUE TITLE
大佬 r2s能不能加个风扇控制？

### ISSUE THREAD

**Issue by liuxiao0725** [kiddin9/OpenWrt_x86-r2s-r4s#427]
RT 我找了找启动项 没有 能不能加个？谢谢
  只要开机就一直转 能不能有个阀值？

**Comment by garypang13** [comment]
没听说过这个功能, 哪个固件有这个功能么,

**Comment by liuxiao0725** [comment]
dayong的就有 风扇到了温度转 不到温度不转貌似是天灵的源码

**Comment by liuxiao0725** [comment]
大佬这个会有吗 风扇控制？> 没听说过这个功能, 哪个固件有这个功能么,

**Comment by kiddin9** [comment]
添加上了.等下一版固件更新.

**Comment by liuxiao0725** [comment]
好的谢谢> 添加上了.等下一版固件更新.

**Comment by L1cardo** [comment]
@kiddin9 请问风扇现在的策略是什么，我的风扇大冬天也在转

**Comment by kiddin9** [comment]
默认是关闭风扇控制的, 需要在 开启启动中启用 fa-fancontrol来开启

**Comment by L1cardo** [comment]
> 默认是关闭风扇控制的, 需要在 开启启动中启用 fa-fancontrol来开启

我开启这个启动项后风扇还是一直转
