### ISSUE TITLE
大佬，x86集成dpdk现阶段有兼容性问题吗？

### ISSUE THREAD

**Issue by avsba001** [kiddin9/OpenWrt_x86-r2s-r4s#428]
我看到有官方文档，openwrt 编译dpdk，但现阶段基本都没有人集成，是有什么问题吗，只有l大测试了下armv7构架的。
`http://doc.dpdk.org/guides/howto/openwrt.html`

**Comment by aikonlee** [comment]
查询一下 DPDK 和 OPENWRT 官方支持的 NIC 、CPU 系列
