### ISSUE TITLE
系统在线更新后未保留已安装软件包

### ISSUE THREAD

**Issue by PetrusZ** [kiddin9/OpenWrt_x86-r2s-r4s#429]
在服务->系统在线更新，勾选保持设置，保留当前配置和保留已安装软件包，从06.12.2021升级到07.06.2021后，系统和插件配置均被保存，但之前已安装的插件，全部消失，需要重新安装。

![image](https://user-images.githubusercontent.com/4990592/125079803-9e755b80-e0f6-11eb-8f43-69e890a134a9.png)

**Comment by qinyixiang11** [comment]
一直有这个问题，还有能否集成DDNS？不然每次升级都要重新装一遍

**Comment by dsyo2008** [comment]
一样问题，所以不敢点更新，其实更新没区别，没发现提升和稳定。

**Comment by Wssfh** [comment]
既然不能备份恢复，应该取消这两个选项，改成提示：升级后所有软件包将会消失，比较好，内网操作还好，向我用DDNS操作，升级完直接失联，还要回去用内网重新配置一遍。
