### ISSUE TITLE
系统在线更新提示签名校验失败

### ISSUE THREAD

**Issue by xseruer** [kiddin9/OpenWrt_x86-r2s-r4s#435]
系统在线更新

当前固件版本【 07.06.2021 】    最新版本号：07.22.2021

![image](https://user-images.githubusercontent.com/4255288/126618096-381f904c-e4c8-48b8-8650-68a3cdf94005.png)

点击更新后弹出如下错误：
Md5 check failed: https://op.supes.top/firmware/nanopi-r4s/07.22-openwrt-rockchip-armv8-nanopi-r4s-squashfs-sysupgrade.img.gz

**Comment by garypang13** [comment]
下载的固件不完整, 刷新页面后重试.

**Comment by xseruer** [comment]
> 下载的固件不完整, 刷新页面后重试.

试过好几次了，从昨天晚上到现在一直都是这样的错误。

**Comment by xseruer** [comment]
重试没用，最后重新刷机才好的。
