### ISSUE TITLE
系统在线更新是会导致路由器硬盘上的东西都被清空的吗？

### ISSUE THREAD

**Issue by wang745125665** [kiddin9/OpenWrt_x86-r2s-r4s#442]
我从06.27升级到07.27我硬盘上放的文件 还有安装的docker镜像全部消失了

**Comment by wang745125665** [comment]
看了一下是将我做的扩容给删除了，我本来是32G的硬盘，刷入固件后只使用了1.5G，然后按照扩容方法，将硬盘全部分给了openwrt，现在更新固件后，又只变成1.5G了

**Comment by kiddin9** [comment]
不要扩容,而是要扩展新分区.
https://t.ly/ccfZ

**Comment by wang745125665** [comment]
@kiddin9 我试试你这个方案，我用的是以前我用过的扩容方案，因为以前的固件不能在线更新
你这个方案扩展新分区，在线升级就不会删除数据了是吗

**Comment by kiddin9** [comment]
当然不会,

**Comment by wang745125665** [comment]
@kiddin9 谢谢解惑
