### ISSUE TITLE
新版本编译时不能用SSH自行配置固件了吗？

### ISSUE THREAD

**Issue by apc337** [kiddin9/OpenWrt_x86-r2s-r4s#448]
新版本的/.github/workflows/repo-dispatcher.yml去掉了SSH手动配置的相关代码
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'

现在自动跳过SSH配置了，我想手动配置一些代码，该怎么办？
谢谢啦！

**Comment by kiddin9** [comment]
使用Readme中介绍的方式2油猴脚本的触发方式. 只需要在type中加上ssh 就会触发ssh
![image](https://user-images.githubusercontent.com/48883331/128666002-5439058a-6171-4c24-b551-a5ce2370fa1e.png)

**Comment by apc337** [comment]
请问这个Type在哪里啊？我没有找到。

**Comment by kiddin9** [comment]
安装好油猴脚本后仓库页面就会看到这个按钮.
![image](https://user-images.githubusercontent.com/48883331/128667207-ba936376-f24f-49b0-b2e1-b334d3c7844e.png)
点击就会弹出对话框.

**Comment by apc337** [comment]
请问弹出的第三个对话框Client Payload (in JSON)，这里填什么？我空着直接点了下一步，然后克隆源代码这一步就出错了

**Comment by kiddin9** [comment]
如果是x86的话就填 
![image](https://user-images.githubusercontent.com/48883331/128667749-4384513d-a9cc-4320-b7c4-ee6862fbb7c0.png)
r2s就填 {"target": "nanopi-r2s"}

**Comment by apc337** [comment]
谢谢

**Comment by a717445834** [comment]
> 使用Readme中介绍的方式2油猴脚本的触发方式. 只需要在type中加上ssh 就会触发ssh
> ![image](https://user-images.githubusercontent.com/48883331/128666002-5439058a-6171-4c24-b551-a5ce2370fa1e.png)

现在只会让填token,请问要如何填写

**Comment by kiddin9** [comment]
你点错按钮了, 要点 Repo Dispatch 按钮才能ssh

**Comment by a717445834** [comment]
> 你点错按钮了



> 你点错按钮了

对不起,我刚刚开始用这个,不是太熟,试了几次,现在已经再编译了,谢谢大佬
