### ISSUE TITLE
nft-qos流量控制没有作用

### ISSUE THREAD

**Issue by Omoinemie** [kiddin9/OpenWrt_x86-r2s-r4s#454]
无论我怎么设置，这个插件一点用都没有，软件流量分载加速也是关了的

**Comment by kiddin9** [comment]
@Omoinemie Mac限速确实有问题, IP限速是正常的.

**Comment by Omoinemie** [comment]
> @Omoinemie Mac限速确实有问题, IP限速是正常的.

就是IP模式啊，你看看我的设置哪里漏了？
![Snipaste_2021-08-17_16-35-51](https://user-images.githubusercontent.com/31991443/129692828-c513523f-6ae0-43de-82b3-5f4fcdb6c1ca.jpg)

![Snipaste_2021-08-17_16-37-03](https://user-images.githubusercontent.com/31991443/129692963-27773479-d282-4a3e-aa3f-71845d098457.jpg)
