### ISSUE TITLE
友善R2S 刷0730固件 菜单栏重启/定时重启使用后需断电才能启动否则无反应

### ISSUE THREAD

**Issue by MapleStoryCms** [kiddin9/OpenWrt_x86-r2s-r4s#456]
hi，如标题所示，烦请大佬翻牌

**Comment by kiddin9** [comment]
为啥不刷最新的0823固件呢,

**Comment by MapleStoryCms** [comment]
> 为啥不刷最新的0823弹呢，

晚上回家更新试试

**Comment by MapleStoryCms** [comment]
版本：OpenWrt 08.23.2021 by Kiddin' / LuCI openwrt-21.02 branch git-ed43006
设备：FriendlyElec NanoPi R2S (CpuMark : 19659.532639 Scores)
更新了也一样，重启以后必须断电一下才能启动；
