### ISSUE TITLE
github actions编译修改IP和替换网卡位置

### ISSUE THREAD

**Issue by a717445834** [kiddin9/OpenWrt_x86-r2s-r4s#463]
请问如果使用github编译的话修改管理IP要如何操作?
是否是修改这个文件
OpenWrt_x86-r2s-r4s/devices/common/default-settings
![image](https://user-images.githubusercontent.com/46695984/131695608-e1d5ab62-7847-40dd-8b27-a366dd896f83.png)
我现在用的是m93p,每次刷进去之后wan口和lan口互换,请问如何通过配置调换网卡位置

**Comment by kiddin9** [comment]
是的,

交换网口复制 https://github.com/kiddin9/OpenWrt_x86-r2s-r4s/blob/master/devices/nanopi-r4s/patches/lan_wan.patch 这个文件到devices/common/patches/目录下

**Comment by a717445834** [comment]
谢谢大佬,马上去试试

**Comment by a717445834** [comment]
> 是的,
> 
> 交换网口复制 https://github.com/kiddin9/OpenWrt_x86-r2s-r4s/blob/master/devices/nanopi-r4s/patches/lan_wan.patch 这个文件到devices/common/patches/目录下

谢谢大佬,我马上去试一下

**Comment by a717445834** [comment]
> 是的,
> 
> 交换网口复制 https://github.com/kiddin9/OpenWrt_x86-r2s-r4s/blob/master/devices/nanopi-r4s/patches/lan_wan.patch 这个文件到devices/common/patches/目录下

您好,我按照这个操作修改文件后编译发现提示错误
![image](https://user-images.githubusercontent.com/46695984/131801196-9499ebc5-0610-4b2d-89e9-69a9b7cdcff2.png)
![image](https://user-images.githubusercontent.com/46695984/131801320-8e70cf25-f1a8-47ee-8e11-2e2d80eef71b.png)
我对比了一下openwrt的源代码,这个补丁包应该没有错,但是不知道为啥编译失败了
我修改了IP,编译成功,然后现在修改网卡位置,发现编译失败了
请问您知道是什么情况吗

**Comment by kiddin9** [comment]
要一模一样复制那个文件,我那个文件有14行,你复制过去就变成12行了,

**Comment by a717445834** [comment]
> 要一模一样复制那个文件,我那个文件有14行,你复制过去就变成12行了,

这么严谨的吗,好的我试一下
我还想再加一个eht2网卡的是不是这样配置?行数也要保持一致
  
--- a/package/base-files/files/etc/board.d/99-default_network
+++ b/package/base-files/files/etc/board.d/99-default_network
@@ -8,8 +8,8 @@ board_config_update
 
 json_is_a network object && exit 0
 
-ucidef_set_interface_lan 'eth0'
-[ -d /sys/class/net/eth1 ] && ucidef_set_interface_wan 'eth1'
+ucidef_set_interface_wan 'eth0'
+[ -d /sys/class/net/eth1 ] && ucidef_set_interface_lan 'eth1'
+[ -d /sys/class/net/eth1 ] && ucidef_set_interface_lan 'eth2'
 board_config_flush
