### ISSUE TITLE
WAN接口PPPOE会自己变成DHCP

### ISSUE THREAD

**Issue by ghost** [kiddin9/OpenWrt_x86-r2s-r4s#464]
之前一直是光猫桥接，软路由拨号，昨天忘记交话费了，今天一觉起来发现没网，赶紧交了话费,过了一会发现还是没网，检查一下发现WAN接口的PPPOE自己协议变成了DHCP。请问这是什么情况，怎么样能解决他自己切换协议的问题，网上搜不到类似情况。
用的X86  08.31.2021

**Comment by HooCookies** [comment]
以前拨号时改PPPOE是从网络WAN接口里切换协议的，刚刚发现设置向导里是这样的(如下图)，是否因此导致协议会自动切换
![1](https://user-images.githubusercontent.com/89955858/131776756-b3d8f51f-3db7-4b16-a22b-d08f461442c2.jpg)

**Comment by a330209159** [comment]
今天早上同样遇到了这样的情况，查看了下，是插件更新了，自己手动改了回去。不知以后还会不会出现这种情况

**Comment by a330209159** [comment]
> 是这个向导插件自动更新后导致的问题.

请问是否有必要卸载次设置向导插件，以保证以后路由器的稳定运行？

如需要卸载，请问此插件英文名是什么

**Comment by kiddin9** [comment]
已经修复, 不会再出现此情况了.
