### ISSUE TITLE
qBittorrent不能保存下载路径问题,不能保存配置,当前配置只在重启前有效,重启丢失

### ISSUE THREAD

**Issue by a717445834** [kiddin9/OpenWrt_x86-r2s-r4s#465]
qBittorrent用luci-app修改下载路径
![image](https://user-images.githubusercontent.com/46695984/131779790-5ead3bb1-1168-4491-bffa-242d7f7b1cfc.png)
用WEBUI修改下载路径
![image](https://user-images.githubusercontent.com/46695984/131779872-34d3634a-65ff-41af-8cbd-b153d2a19866.png)
只要一重启进程或者机器,打开WEBUI设置发现下载地址又被还原成/etc/qBittorrent/downloads/了
查看启动文件vim /etc/init.d/qbittorrent
发现有关于启动路径的设置
![image](https://user-images.githubusercontent.com/46695984/131779937-9802c62a-6d7d-48a9-9c7b-68fb2c97b636.png)
但是修改后重启还是无效,而且还会报错
![image](https://user-images.githubusercontent.com/46695984/131779982-7a556cea-e395-424e-a4c1-b9b27b59aa7b.png)
不知道是哪里的问题

**Comment by a717445834** [comment]
已解决
修改vim /etc/init.d/qbittorrent
通过多次的测试发现
![image](https://user-images.githubusercontent.com/46695984/131814408-6daba246-4a53-4e26-944f-5968933c36f3.png)
重启服务的时候它会检查你是否存在配置,如果存在,那么就修改你配置文件的这两项,但是他修改的有问题,所以导致配置文件乱七八糟,我直接注释了,然后再输出一个666表示对自己的肯定

**Comment by kiddin9** [comment]
测试了没遇到你说的这个情况,

**Comment by kiddin9** [comment]
@kiddin9 下载路径以luci中设置的为准,

**Comment by a717445834** [comment]
> @kiddin9 下载路径以luci中设置的为准,

我把QB的配置文件删除,然后通过luci保存并应用,他的下载路径就没问题,然后再通过luci修改下载路径,他就会出错了
