### ISSUE TITLE
GFW模式联不通

### ISSUE THREAD

**Issue by Omoinemie** [kiddin9/OpenWrt_x86-r2s-r4s#466]
bypass用gfw模式联不通，改成智能模式可以通了，再改回GFW模式就好了，但是过一段时间又不通了。
![Snipaste_2021-09-02_16-36-17](https://user-images.githubusercontent.com/31991443/131811729-02c11f34-af59-4f8c-affc-a52ece5fbc50.jpg)

**Comment by HHHCCCooo** [comment]
我这边也遇到一样情况了,大概是因为GFW列表一直下载不下来
![1](https://user-images.githubusercontent.com/89955858/131829799-1870dd00-2788-4ccb-8c83-450b0363137d.jpg)

**Comment by a717445834** [comment]
我之前也是遇到这个问题了,但是搞其他的重刷了,现在暂时还没遇到

**Comment by BanKnight** [comment]
我也碰到类似问题

**Comment by kiddin9** [comment]
已修复.
