### ISSUE TITLE
Bypass与与AdGuardHome搭配使用的问题

### ISSUE THREAD

**Issue by Mabisi** [kiddin9/OpenWrt_x86-r2s-r4s#473]
是不是只要打开bypass的与adg一起使用的开关就可以了啊？还有这两个地方都是默认的是否还需要配置吗？
+
+
![image](https://user-images.githubusercontent.com/19968269/132999122-46a5d003-9dff-4e71-ac8a-288493a74ff0.png)
![image](https://user-images.githubusercontent.com/19968269/132999127-b838464c-d616-4921-b4a9-8c049b79665b.png)

**Comment by kiddin9** [comment]
只需要在bypass打勾就行, 不需要配置adg,

**Comment by Mabisi** [comment]
> 只需要在bypass打勾就行, 不需要配置adg,

就是安装安装完adg然后bypass打开这个选项就可以了哇

**Comment by kiddin9** [comment]
是的, 有没成功你看下adg的查询记录就知道了,

**Comment by Mabisi** [comment]
> 是的, 有没成功你看下adg的查询记录就知道了,

好的！谢谢
