### ISSUE TITLE
usb硬盘共享问题

### ISSUE THREAD

**Issue by lzqd** [kiddin9/OpenWrt_x86-r2s-r4s#475]
9.13版固件usb硬盘共享问题
在连接上一个14T的usb硬盘盒后固件卡死
重启后登录界面都无法进入
X86的设备

**Comment by kiddin9** [comment]
不连接USB硬盘盒重启也进不了登录界面么,

**Comment by lzqd** [comment]
> 不连接USB硬盘盒重启也进不了登录界面么，
拔掉USB硬盘盒就没问题了，是硬盘太大了吗？

**Comment by kiddin9** [comment]
应该是硬盘太大,供电不足导致的.

**Comment by lzqd** [comment]
> 应该是硬盘太大,供电不足导致的.

3.5寸硬盘盒有外接电源的，功率充足。

**Comment by nullllunA** [comment]
我有个类似问题，不过不是插上移动硬盘后固件卡死（我的这一步很正常，我的硬盘是希捷1T哈），但是如果路由器重启的话不能正常引导进系统，屏幕黑屏无显示不知道状态，如果拔掉移动硬盘再重启就没问题。嗯我接的移动硬盘是非引导的NTFS格式的，另外已经设置了启动项是EMMC里面的UEFI第一。我的是emmc的SD卡，wyse 5070.
