### ISSUE TITLE
请求增加ixgbevf驱动

### ISSUE THREAD

**Issue by jy00240317** [kiddin9/OpenWrt_x86-r2s-r4s#480]
我的网卡是X550 T2，开启SRIOV后，固件不识别网卡，我使用.SH脚本自己编译后，启动一直卡booting the kernel，原因不明。请求大佬增加ixgbevf驱动进编译。感谢。

**Comment by kiddin9** [comment]
已增加, 重刷最新固件即可.

**Comment by jy00240317** [comment]
已上机，完美运行，感谢大佬的帮助。
