### ISSUE TITLE
为什么 AdGuardHome 的核心，0.106.3 会比 0.107.0 更新？ 

### ISSUE THREAD

**Issue by aQuaYi** [kiddin9/OpenWrt_x86-r2s-r4s#482]
![image](https://user-images.githubusercontent.com/6028869/134532232-72abe2e9-e68c-494f-8eb4-788741eab6f7.png)

![image](https://user-images.githubusercontent.com/6028869/134532334-18d57052-59f9-4c63-bd12-0adf48fb119b.png)

点击更新后，会出现问题。

折腾了好久才恢复。

**Comment by kiddin9** [comment]
这个你得问adguardhome...

**Comment by C018** [comment]
因为你更新链接用的标准版，换成测试版就正常了
