### ISSUE TITLE
大佬能出一个r2c的版本么？

### ISSUE THREAD

**Issue by HGG233** [kiddin9/OpenWrt_x86-r2s-r4s#483]
准备买第二个r2s的，但是现在r2s太贵了，就入了个r2c。后来发现一直用的小鸡大佬的固件没r2c版本，大佬能不能有空包容下r2c用户。

**Comment by kiddin9** [comment]
https://op.supes.top/firmware/nanopi-r2c/

**Comment by HGG233** [comment]
谢谢大佬
