### ISSUE TITLE
Adguard home和bypass 搭配使用问题 【已参考#473】

### ISSUE THREAD

**Issue by avsba001** [kiddin9/OpenWrt_x86-r2s-r4s#484]
[https://github.com/kiddin9/OpenWrt_x86-r2s-r4s/issues/473](url)
![截图_20212501012540](https://user-images.githubusercontent.com/29015932/135569828-29807d05-313c-4938-9cde-0f7bf53e4449.png)
![截图_20212501012549](https://user-images.githubusercontent.com/29015932/135569841-29744ef5-6b96-4649-abe6-c70e97da4172.png)
参考上述issus配置后adg并无生效，已开启日志，是否新版修改了需要另行配置

**Comment by kiddin9** [comment]
查看后台 adguardhome插件的设置界面是否显示 已重定向 重定向是否已自动设置为 使用53端口替换dnsmasq

**Comment by avsba001** [comment]
> 查看后台 adguardhome插件的设置界面是否显示 已重定向 重定向是否已自动设置为 使用53端口替换dnsmasq

查明白了，adguardhome插件不能先启用再勾选bypass的选项，要在adguardhome插件关闭的情况下勾选
