### ISSUE TITLE
后台404

### ISSUE THREAD

**Issue by tong-mo** [kiddin9/OpenWrt_x86-r2s-r4s#497]
升级后进后台显示404，重新刷一遍固件联网后后台也404，这是怎么回事？

**Comment by aQuaYi** [comment]
> 命令行 执行
> 
> sed -i 's//cgi-bin//' /etc/nginx/conf.d/luci.locations
> service nginx restart

我的设备也是 R2S，应该是开启了自动更新功能。刚刚想进入后台，也是显示404页面。

我现在使用 ssh 进入了设备的命令行。在执行`sed -i 's//cgi-bin//' /etc/nginx/conf.d/luci.locatio
ns` 时，显示的结果是

`sed: bad option in substitution expression`

**Comment by kiddin9** [comment]
```
sed -i 's/\/cgi-bin//' /etc/nginx/conf.d/luci.locations
service nginx restart
```

**Comment by aQuaYi** [comment]
感谢
