### ISSUE TITLE
web端口更改

### ISSUE THREAD

**Issue by Duneon** [kiddin9/OpenWrt_x86-r2s-r4s#500]
系统设置里面看不到Web管理啊，怎样修改？
我需要使用这个https://github.com/skydevil88/XboxDownload/blob/master/README_OpenWrt.md

**Comment by kiddin9** [comment]
没有安装uhttpd,用的就是nginx, 所有不需要更改端口和安装nginx这一步,

**Comment by Duneon** [comment]
nginx_init: NOT using conf file!
show config to be used by: nginx -T -c '/etc/nginx/uci.conf'


> 没有安装uhttpd,用的就是nginx, 所有不需要更改端口和安装nginx这一步,

我跳过那两个步骤SSH进路由编辑好xbox.conf后直接执行/etc/init.d/nginx restart命令报错

nginx_init: NOT using conf file!
show config to be used by: nginx -T -c '/etc/nginx/uci.conf'

**Comment by kiddin9** [comment]
我测试了没问题, nginx -T -c '/etc/nginx/uci.conf 看报什么错,

**Comment by Duneon** [comment]
> nginx_init: NOT using conf file! show config to be used by: nginx -T -c '/etc/nginx/uci.conf'
> 
> > 没有安装uhttpd,用的就是nginx, 所有不需要更改端口和安装nginx这一步,
> 
> 我跳过那两个步骤SSH进路由编辑好xbox.conf后直接执行/etc/init.d/nginx restart命令报错
> 
> nginx_init: NOT using conf file! show config to be used by: nginx -T -c '/etc/nginx/uci.conf'

**Comment by Duneon** [comment]
> 我测试了没问题, nginx -T -c '/etc/nginx/uci.conf 看报什么错,

没有信息显示，只有一个 > 符号

**Comment by kiddin9** [comment]
nginx -T -c '/etc/nginx/uci.conf'

**Comment by Duneon** [comment]
> nginx -T -c '/etc/nginx/uci.conf'

 [emerg] 18128#0: could not build server_names_hash, you should increase server_names_hash_bucket_size: 32
nginx: configuration file /etc/nginx/uci.conf test failed

**Comment by Duneon** [comment]
> nginx -T -c '/etc/nginx/uci.conf'

大佬还在看吗

**Comment by Duneon** [comment]
解决了，代码上面加个server_names_hash_bucket_size 64
数字可以改，32倍数往上加，64  128 512
web端口还是要改8080

**Comment by Duneon** [comment]
> 

https://bbs.a9vg.com/forum.php?mod=viewthread&tid=8781059&mobile=2

**Comment by cwdsun** [comment]
> 
十分感谢，很有帮助。加了代码就成功了。
我没改8080端口，也能成功跳转

**Comment by lan852** [comment]
> 

这个代码怎么加啊？   加在哪里呢
