### ISSUE TITLE
微软1663 USB3.0有线网卡驱动

### ISSUE THREAD

**Issue by wangyangxiaoyuer** [kiddin9/OpenWrt_x86-r2s-r4s#501]
微软1663 USB3.0有线网卡驱动请添加一下，芯片是RTL8153

**Comment by kiddin9** [comment]
应该是有添加的吧,你测试了么,

**Comment by wangyangxiaoyuer** [comment]
初步看下来，插入没有驱动，软件包里也没看到

**Comment by kiddin9** [comment]
kmod-usb-net-rtl8152-vendor 是有添加的, 不知道是不是这个驱动,

**Comment by wangyangxiaoyuer** [comment]
晚上又试了，还是不行，插上去没反应，驱动不了，麻烦大神排查下
