### ISSUE TITLE
固件作为旁路由网络该如何设置呢

### ISSUE THREAD

**Issue by madman43** [kiddin9/OpenWrt_x86-r2s-r4s#508]
这是网络配置，我已经把默认桥接取消了，填入了ip但是还是ping不出去
![1](https://user-images.githubusercontent.com/19260034/141270479-4db19ba0-8ad7-47e9-96fc-d263225e200a.png)
![2](https://user-images.githubusercontent.com/19260034/141270775-2af7fd4d-f2ef-4872-8af1-830fd688f44f.png)
![3](https://user-images.githubusercontent.com/19260034/141270780-51559d94-38f4-48eb-ad31-c759e2f2e0f9.png)
![4](https://user-images.githubusercontent.com/19260034/141270787-f4c1301f-0b18-46fa-9b1a-a830d42204a9.png)

还望能够指导下，感激不尽

**Comment by kiddin9** [comment]
网关指向主路由, 设置DNS, 关闭DHCP,  其他都不用设置

**Comment by madman43** [comment]
一直没用过新版openwrt，现在直接设置就好了，太方便了，感谢

**Comment by qifei** [comment]
此时旁路由的 LAN 口接主路由的 LAN 口对吗？，然后如何管理旁路由？
谢谢

**Comment by madman43** [comment]
> 此时旁路由的 LAN 口接主路由的 LAN 口对吗？，然后如何管理旁路由？ 谢谢

旁路由的 LAN 口接主路由的 LAN 口，ip填同网段ip，关闭dhcp即可

**Comment by qifei** [comment]
已经连上了，谢谢。并没有别人说的那么难。
