### ISSUE TITLE
是否可以在固件发布处增加VMDK以方便使用Macbook的童鞋？

### ISSUE THREAD

**Issue by leizhiren** [kiddin9/OpenWrt_x86-r2s-r4s#509]
MacOSMonterey的Brew安装不了qemu，无法自行转换为vmdk，还得再装个windows虚拟机，相当繁琐。建议作者能直接提供。

**Comment by kiddin9** [comment]
VMDK给exsi用吗 固件直接编译出来的vmdk缺少flat.vmdk没办法直接使用的,  建议用PVE虚拟机
