### ISSUE TITLE
关于在Openwrt中运行PVE。

### ISSUE THREAD

**Issue by leizhiren** [kiddin9/OpenWrt_x86-r2s-r4s#510]
![1636958114(1)](https://user-images.githubusercontent.com/24837873/141733741-c4a94f32-9dad-4016-8250-020a2237227a.jpg)

在Openwrt中还可以运行PVE？大佬，怎么操作？

**Comment by leizhiren** [comment]
可以的话就不用虚拟Openwrt那么麻烦了

**Comment by kiddin9** [comment]
里面大部分的服务都需要自己装的,这个只是提供一个快捷访问的入口.

**Comment by leizhiren** [comment]
如何装PVE，在Openwrt里？搜到都是PVE装Openwrt，没搜到有Openwrt装PVE的相关资料。大佬指导一二。

**Comment by kiddin9** [comment]
是PVE装Openwrt ,只不过装好后你可以使用 pve/ 访问pve管理后台 
![image](https://user-images.githubusercontent.com/48883331/141735292-76a41899-5f39-49a6-ba5f-edd18e7d2f05.png)

**Comment by leizhiren** [comment]
了解了。是我误读了
