### ISSUE TITLE
build.sh 脚本有问题

### ISSUE THREAD

**Issue by OUZYcn** [kiddin9/OpenWrt_x86-r2s-r4s#516]
OS：ubuntu-20.10-live-server-amd64
Repo：http://mirrors.aliyun.com/ubuntu/ groovy

编译的脚本：
https://raw.githubusercontent.com/kiddin9/OpenWrt_x86-r2s-r4s/master/onekey/build.sh

这段会出错：：
sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev **libz-dev** patch python3 python2.7 unzip zlib1g-dev **lib32gcc1** libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler ccache xsltproc rename antlr3 gperf curl screen **upx** jq

要换成：
sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev **zlib1g-dev** patch python3 python2.7 unzip zlib1g-dev **lib32gcc-s1** libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler ccache xsltproc rename antlr3 gperf curl screen **upx-ucl** jq

最后开始编译前，有出错的：

```
cat: /home/ouzy/openwrt/tmp/info/.files-packageinfo-64969: No such file or directory
/bin/sh: 3: cannot open /home/ouzy/openwrt/tmp/info/.files-packageinfo-64969: No such file
cat: /home/ouzy/openwrt/tmp/info/.files-packageinfo-64865: No such file or directory
/bin/sh: 3: cannot open /home/ouzy/openwrt/tmp/info/.files-packageinfo-64865: No such file
WARNING: Makefile 'package/feeds/custom/luci-app-k3screenctrl/Makefile' has a dependency on 'phicomm-k3screenctrl', which does not exist
Checking 'rsync'... ok.
time: target/linux/prereq#0.20#0.11#0.27
```

不知道是不是这里的原因
```
make -j$(($(nproc)+1)) download -j$(($(nproc)+1)) &
make -j$(($(nproc)+1)) || make -j1 V=s

```

**Comment by kiddin9** [comment]
感谢指正, 已修复.  开始编译前的那个报错可以无视.
