### ISSUE TITLE
R2s做旁路由软件包更新列表失败

### ISSUE THREAD

**Issue by BlackBlueBin** [kiddin9/OpenWrt_x86-r2s-r4s#523]
![image](https://user-images.githubusercontent.com/19592304/143990093-8c86b673-0bc2-4732-8931-e1049d91fca7.png)
此固件用在R2S上，用来做旁路由。在软件包->更新列表,出现上图的错误，不知道是哪里设置的有问题。浏览器直接访问：
https://op.supes.top/packages/aarch64_generic/routing/Packages.gz 是能够直接下载Packages.gz到本地的。
还有一个问题是，bypass在设置完后，运行模式选的GFW列表模式，无法上网，更改为智能模式就可以，但是在bypass的界面，百度链接是失败的结果。但是不影响访问。 
![image](https://user-images.githubusercontent.com/19592304/143990620-a84df7e0-2b5a-4f6b-ba28-af76fad2f787.png)

是我的旁路由有地方设置不对吗？

**Comment by kiddin9** [comment]
系统 -> 设置向导 -> 网络设置 -> 勾选旁路由模式⁠

**Comment by BlackBlueBin** [comment]
> 系统 -> 设置向导 -> 网络设置 -> 勾选旁路由模式⁠

请问勾选了旁路由模式后，还要做什么其他的设置吗？
