### ISSUE TITLE
插了一个优越者USB2.5G网卡上去，只能识别成千兆网卡

### ISSUE THREAD

**Issue by yahochina** [kiddin9/OpenWrt_x86-r2s-r4s#524]
不知道是不是驱动问题？芯片是RTL8156B，小白一枚，不知如何能搞定这个驱动，系统是：OpenWrt 11.24.2021 by Kiddin' / LuCI openwrt-21.02 branch git-13df80d

**Comment by kiddin9** [comment]
ethtool -s eth4 autoing off
ethtool -s eth4 speed 2500
