### ISSUE TITLE
关于intel i225网卡

### ISSUE THREAD

**Issue by jackyue-github** [kiddin9/OpenWrt_x86-r2s-r4s#525]
软件包：kmod-igc缺失，无法上网

**Comment by jackyue-github** [comment]
![Uploading 27BCF335-7036-440F-A564-7C1F7170ADB0.jpeg…]()

**Comment by jackyue-github** [comment]
![BA798F12-7F22-4D1E-A6FA-079791A6E9C1](https://user-images.githubusercontent.com/80149330/144384051-c191c327-541e-4b46-845a-87044da9f649.jpeg)

**Comment by kiddin9** [comment]
@jackyue-github 下一版加上.

**Comment by jackyue-github** [comment]
![Uploading FAB06613-C9AA-4D15-9068-9B55F9C78338.jpeg…]()

**Comment by jackyue-github** [comment]
发出去了，没显示

**Comment by jackyue-github** [comment]
> @jackyue-github下一个版本加上。

![E4BB4ABB-2A5A-495F-B33F-9BA13D0E3D1E](https://user-images.githubusercontent.com/80149330/144393658-bd474326-4625-4972-a0f0-499dc7bc5e2a.jpeg)

**Comment by jackyue-github** [comment]
wan变成lan口，

**Comment by jackyue-github** [comment]
r4s固件也是用你编译的非常稳定😁
