### ISSUE TITLE
8125网卡没有驱动起来

### ISSUE THREAD

**Issue by veik** [kiddin9/OpenWrt_x86-r2s-r4s#527]
才发现最近一版2.5G 8125网卡只能到千兆。不知道是否是我的个案。刷其他的固件可以驱动起来2.5G

**Comment by kiddin9** [comment]
刷今天的最新固件试试,

**Comment by veik** [comment]
在等你最新编译的

**Comment by kiddin9** [comment]
@veik 最新固件网速正常了麽

**Comment by veik** [comment]
用你昨天傍晚编译的版本进去还是显示千兆。

**Comment by steamch** [comment]
一样的问题

**Comment by steamch** [comment]
螃蟹2.5G网卡无论是板载还是usb网卡都会设别成千兆，其他固件没问题

**Comment by veik** [comment]
螃蟹2.5G网卡有识别出来了不？我想换回这个固件来
