### ISSUE TITLE
R4S更换LAN口IP后重启，nginx进程无法启动

### ISSUE THREAD

**Issue by YUMEYA** [kiddin9/OpenWrt_x86-r2s-r4s#532]
环境：R4S LAN、WAN口均配置了PPPOE拨号连接光猫，通过USB网卡连接AP模式的无线路由器，USB网卡配置的静态IP是10.1.1.1
现象：重启后SSH可以登录，Web界面提示访问被拒绝，查看进程nginx未启动，查看日志有nginx启动失败报配置错误的记录：
![image](https://user-images.githubusercontent.com/17715365/144859732-657caf76-72fe-4745-8fb9-316d7915156d.png)
对应行的配置：
![image](https://user-images.githubusercontent.com/17715365/144860714-c0163835-95c7-4ca3-890e-7ccdbbf1abc8.png)
不加载shortcuts.conf时nginx可以正常启动

**Comment by kiddin9** [comment]
lan使用USB网卡的缘故,导致获取lan口IP生成shortcuts.conf失败了,
删掉shortcuts.conf文件的话下回更新固件就又有了,直接把shortcuts.conf里的内容清空吧,

**Comment by YUMEYA** [comment]
> lan使用USB网卡的缘故,导致获取lan口IP生成shortcuts.conf失败了, 删掉shortcuts.conf文件的话下回更新固件就又有了,直接把shortcuts.conf里的内容清空吧,

好的，谢谢大佬
