### ISSUE TITLE
无法卸载Bypass

### ISSUE THREAD

**Issue by 1900forever** [kiddin9/OpenWrt_x86-r2s-r4s#533]
luci-app-bypass
人在墙外，不需要这个插件，但是尝试多次卸载都无法完成。
本想尝试看是否能通过先升级插件再卸载的方式来完成卸载，结果提示
Collected errors:
 * opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.
opkg upgrade 命令失败，代码 255。

**Comment by hy817120** [comment]
可以卸载的，我卸载了，不过我是自己设置了smartdns配合ssr上网使用，然后再卸载了 再重启了，

**Comment by dino1928** [comment]
rm  /var/lock/opkg.lock
