### ISSUE TITLE
warning: Could not find remote branch v to clone.

### ISSUE THREAD

**Issue by FENNY521** [kiddin9/OpenWrt_x86-r2s-r4s#538]
编译时，在clone source code 这一步出现
jq: error (at <stdin>:4): Cannot iterate over null (null)
Cloning into 'openwrt'...
**warning: Could not find remote branch v to clone.**
fatal: Remote branch v not found in upstream origin
Error: Process completed with exit code 128.
请问是什么原因啊

**Comment by iwrt** [comment]
全新替换掉 - name: Clone source code 这段代码即可。

**Comment by kiddin9** [comment]
在 Settings->Secrets  中设置 REPO_TOKEN 环境变量
