### ISSUE TITLE
10.0.0.1不能进入后台

### ISSUE THREAD

**Issue by L1cardo** [kiddin9/OpenWrt_x86-r2s-r4s#541]
`10.0.0.1`不能进入后台，但是`op/`却可以进入，请问是什么原因
`10.0.0.1`后网页显示如下
<img width="802" alt="image" src="https://user-images.githubusercontent.com/33802186/146577077-bf4e2774-3d24-45e5-80fa-c53931a1ed11.png">

**Comment by iwrt** [comment]
输入  op/  即可

**Comment by L1cardo** [comment]
> 输入  op/  即可   因为nginx

我知道op/可以，我不是说了吗

**Comment by iwrt** [comment]
op/=10.0.0.1:80  不带端口你就无法访问，因为开了nginx。
