### ISSUE TITLE
怎么挂载SMB啊？

### ISSUE THREAD

**Issue by Omoinemie** [kiddin9/OpenWrt_x86-r2s-r4s#542]
用了各种方法，网上也搜遍了，都没挂载成功，机器是R2S。
mount -t cifs和mount.cifs都不行，求指导！

**Comment by Omoinemie** [comment]
那个luci-app-cifs也挂载不上去！

**Comment by kiddin9** [comment]
luci-app-cifs-mount

**Comment by Omoinemie** [comment]
是这个，挂不上去

**Comment by Omoinemie** [comment]
![Snipaste_2021-12-20_16-50-08](https://user-images.githubusercontent.com/31991443/146739532-d95ddcd2-74c4-4183-9cc2-fab66b13bba1.jpg)
用命令行是这个结果：
`root@OPENWRT 16:52 mnt# mount.cifs //192.168.31.3/Disk-1T/ /mnt/ -o user=*,pass=*,rw,vers=1.0
mount.cifs: bad UNC (、//192.168.31.3/Disk-1T/)`

**Comment by Omoinemie** [comment]
我解决了，那个界面里的挂载点要用\而不能用/

**Comment by hy817120** [comment]
先在挂载点挂载好 然后,这么设置就行了,这个固件,不需要去输入什么领命,增加什么或者删除什么,可以直接挂载的.我就是这样,前段时间把固件玩坏了,直接恢复了出厂,然后重新挂载的.
![111](https://user-images.githubusercontent.com/46050478/147350017-e28dcb2a-022b-4b83-aee1-0d11d73af617.jpg)

**Comment by hy817120** [comment]
自带的就有smb,我用的就是自带了的,没下载任何东西,很简单的, 如果要配合aria2,记得以root用户运行就行了.

**Comment by hy817120** [comment]
![111](https://user-images.githubusercontent.com/46050478/147350554-60350be6-42de-4ec1-b1ef-3c38ffdfe4e3.jpg)
![222](https://user-images.githubusercontent.com/46050478/147350557-e7ec5d72-7034-46f9-95c0-6c73009ff09e.jpg)
![333](https://user-images.githubusercontent.com/46050478/147350560-3c32efa7-1f53-424d-8351-6cc9c56ff751.jpg)

**Comment by Omoinemie** [comment]
> 自带的就有,不用去乱改东西 先在挂载点挂载好然后设置就行了，这个不需要去输入什么命令。我就是这样，前段时间把固件玩坏了，直接恢复出厂，然后重新挂载的。 ![111](https://user-images.githubusercontent.com/46050478/147350554-60350be6-42de-4ec1-b1ef-3c38ffdfe4e3.jpg) ![222](https://user-images.githubusercontent.com/46050478/147350557-e7ec5d72-7034-46f9-95c0-6c73009ff09e.jpg) ![333](https://user-images.githubusercontent.com/46050478/147350560-3c32efa7-1f53-424d-8351-6cc9c56ff751.jpg) ![444](https://user-images.githubusercontent.com/46050478/147350724-bb40219f-1369-4de4-b55c-4a19b17df52b.jpg)

我是路由器挂载smb，不是分享smb

**Comment by daiwei43211** [comment]
我也遇到同样的问题啊！是否可以联系到你吗？我的微信：747376326@qq.com

**Comment by hy817120** [comment]
> > 自带的，不用去乱改东西先在挂载好然后设置就行了，这个不需要去什么命令。挂载的。 ![111](https://user-images.githubusercontent.com/46050478/147350554-60350be6-42de-4ec1-b1ef-3c38ffdfe4e3.jpg) ![222](https://user-images.githubusercontent.com/46050478/147350557-e7ec5d72-7034-46f9-95c0-6c73009ff09e.jpg) ![333](https://user-images.githubusercontent.com/46050478/147350560-3c32efa7-1f53-424d-8351-6cc9c56ff751.jpg) ![444](https://user-images.githubusercontent.com/46050478/147350724-bb40219f-1369-4de4-b55c-4a19b17df52b.jpg)
> 
> 我是主机挂载，不是分享

你是路由器扩容吗? 如果是扩容,感觉直接挂载在目录下不就行了吗?  不过没试过,我没扩容,
