### ISSUE TITLE
build.sh

### ISSUE THREAD

**Issue by OUZYcn** [kiddin9/OpenWrt_x86-r2s-r4s#544]
https://github.com/kiddin9/OpenWrt_x86-r2s-r4s/blob/c8e2542453a4e7adf4bb531f5e84cd42c6782c1d/onekey/build.sh#L85

{"message":"API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

**Comment by kiddin9** [comment]
歇会, 你访问github api过于频繁, 把每小时5000次的配额次数都干完了, 或者是 github抽风了,
