### ISSUE TITLE
关于 kmod-usb-net-rtl8152 和 kmod-usb-net-rtl8152-vendor 的问题

### ISSUE THREAD

**Issue by EuropeanWithSSR** [kiddin9/OpenWrt_x86-r2s-r4s#547]
我使用的 orico 品牌 USB 网卡使用带 “vendor” 的驱动无法稳定运行，速度稍快就会崩溃，换成前者则无问题。据说前者是原版驱动，不知道后者有什么修改？
能否麻烦您在软件包中提供前者的更换选项，或者默认采用不带 “vendor” 的驱动，亦或是在升级安装过程中能不修改这个驱动？
如果不好搞的话就算了，感谢！

**Comment by gxhunter1982** [comment]
因为前者驱动的问题，才切换到后者的版本。vendor版就是厂商版本。
同一个设备的驱动没法同时两个存在，只能编译时选择。

**Comment by tonysky2002** [comment]
绿联的2.5g usb网卡也有同样问题。 下载速度稍快就会崩溃。。。
