### ISSUE TITLE
因为固件集成了smartdns-le，所以无法安装原版smartdns，也就是无法使用 luci-app-smartdns  

### ISSUE THREAD

**Issue by moxuanyuan** [kiddin9/OpenWrt_x86-r2s-r4s#549]
希望大神可以改进一下。。

**Comment by kiddin9** [comment]
@moxuanyuan 早几个版本就已经去掉了smartdns-le了

**Comment by moxuanyuan** [comment]
> @moxuanyuan 早几个版本就已经去掉了smartdns-le了

luci-app-smartdns 里一直提示 “SmartDNS - 未运行”，怎样解决？

**Comment by kiddin9** [comment]
关闭bypass

**Comment by moxuanyuan** [comment]
> 关闭bypass

意思是不能跟luci-app-smartdns 同时运行？我试了，关了bypass，确实可以，但只要一开bypass，就不行。。难度不能同时运行吗？

**Comment by kiddin9** [comment]
bypass里已经集成了smartdns, 里面的smartdns是由bypass控制的, 当然与luci-app-smartdns冲突了,

**Comment by moxuanyuan** [comment]
如果我想自定义smartdns 配置应该怎样搞？

**Comment by moxuanyuan** [comment]
还有一个问题，在` 软件包 - 筛选器` 里输入 `smartdns`  在 `可用` 里点升级，是升级不了，是不是因为smartdns版本是内置的，跟软件仓库里的不一样，不能手动升级？

**Comment by gxhunter1982** [comment]
> 还有一个问题，在` 软件包 - 筛选器` 里输入 `smartdns` 在 `可用` 里点升级，是升级不了，是不是因为smartdns版本是内置的，跟软件仓库里的不一样，不能手动升级？

可用的版本和已安装的不一样，都会在“可用”栏里显示“升级”选项。哪怕是可用库里的版本比已安装的旧，也会这么显示。
你应该去“升级”栏里看，有没有真正能升级的。

**Comment by gxhunter1982** [comment]
> 还有一个问题，在` 软件包 - 筛选器` 里输入 `smartdns` 在 `可用` 里点升级，是升级不了，是不是因为smartdns版本是内置的，跟软件仓库里的不一样，不能手动升级？

今日最新版测试下来，已无这个问题
