### ISSUE TITLE
ksmbd重启后不会自动启动

### ISSUE THREAD

**Issue by fucktimi** [kiddin9/OpenWrt_x86-r2s-r4s#552]
我配置好了smb，登陆读写均正常，但是重启机器之后，登陆显示端口未开启，必须登陆后台ksmbd配置界面重新点保存应用后才能开启服务。另外在启动项里面点开启、重启ksmbd也是无效的。

**Comment by kiddin9** [comment]
@fucktimi 软件包中更新下 autoshare-ksmbd

**Comment by fucktimi** [comment]
> @fucktimi 软件包中更新下 autoshare-ksmbd

更新后能够正常启动了。
