### ISSUE TITLE
2021-12-29版固件的AdGuardHome日志时间不对

### ISSUE THREAD

**Issue by lucktu** [kiddin9/OpenWrt_x86-r2s-r4s#554]
12-20版本也有这样的问题

既然您的 bypass 需要 AdGuardHome 合作启动，何不一起带入一个稳定版呢？我安装以后，进入 服务--AdGuardHome--日志，本地时间的勾始终是勾上的，此时显示的时间比实际时间多8个小时。能不能让那个勾可以设置并保持某种状态？即使再回来也不会变？

我用的 linux-x64 docker 版 openwrt，做旁路使用的。

感谢您的固件！

**Comment by kiddin9** [comment]
bypass 并不需要 AdGuardHome 合作启动, adg需要的人不多,且体积太大, 不会包含在默认中

时间问题已修复. 等插件更新即可.

**Comment by lucktu** [comment]
好的，明白！

**Comment by lucktu** [comment]
> bypass 并不需要 AdGuardHome 合作启动, adg需要的人不多,且体积太大, 不会包含在默认中
> 
> 时间问题已修复. 等插件更新即可.

老大测试了吗？我测试的是，现在那个打勾是去掉了，但是时间还是一样的多8个小时，请继续更正。

**Comment by lucktu** [comment]
已修复，多谢！
