### ISSUE TITLE
R4S定制系统升级无法使用

### ISSUE THREAD

**Issue by PKC278** [kiddin9/OpenWrt_x86-r2s-r4s#575]
1.23 r4s固件使用定制系统升级一直报错无法使用

**Comment by kiddin9** [comment]
修复了,再试试.

**Comment by PKC278** [comment]
![image](https://user-images.githubusercontent.com/52959804/150946537-d2473585-d18a-44cd-a955-3f2a4e1019e5.png)
还是不行，另外你的网站https://supes.top 的ssl证书失效了

**Comment by kiddin9** [comment]
不好意思,我忘记改地址了,把 
![image](https://user-images.githubusercontent.com/48883331/150949694-62b50081-dcdb-4398-b879-32ab08596a60.png)
改成 https://op.supes.top
https://supes.top 没使用了,换成了 https://bf.supes.top/

**Comment by PKC278** [comment]
x86/64的没有问题，但是r4s的我试了好多次都显示asu.build.ImageBuildError

**Comment by PKC278** [comment]
https://bf.supes.top/从这里直接下载的R4S固件1.23版没有网卡驱动

**Comment by PKC278** [comment]
感谢大佬的修复，现在已经可以用了
