### ISSUE TITLE
2.6 版本aria2 403提示账户没有权限访问下载的目录

### ISSUE THREAD

**Issue by madman43** [kiddin9/OpenWrt_x86-r2s-r4s#583]
Tue Feb  8 22:50:36 2022 daemon.info aria2: Aria2 will run with user 'aria2'.
Tue Feb  8 22:50:36 2022 daemon.info aria2: Please make sure user 'aria2' has write access to download dir: /mnt/sdc1
Tue Feb  8 22:50:38 2022 daemon.err nginx[2956]: 2022/02/08 22:50:38 [error] 2995#0: *302 directory index of "/www/ariang/" is forbidden, client: 192.168.2.20, server: op, request: "GET /ariang/ HTTP/1.1", host: "192.168.2.2", referrer: "http://192.168.2.2/luci/admin/services/aria2/config"
Tue Feb  8 22:50:47 2022 authpriv.info dropbear[4740]: Child connection from 192.168.2.20:6875
Tue Feb  8 22:50:47 2022 authpriv.notice dropbear[4740]: Password auth succeeded for 'root' from 192.168.2.20:6875
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 8 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 9 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 10 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 11 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 12 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 13 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 14 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 15 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:07 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:08 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:08 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:08 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 1 (Audio: aac, 48000 Hz, 2 channels): unspecified sample format
Tue Feb  8 22:51:08 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:08 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:08 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:08 2022 daemon.err minidlnad[13975]: [matroska,webm @ 0x1e2c3c0] Could not find codec parameters for stream 8 (Subtitle: hdmv_pgs_subtitle): unspecified size
Tue Feb  8 22:51:08 2022 daemon.err minidlnad[13975]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
Tue Feb  8 22:51:39 2022 daemon.err nginx[2956]: 2022/02/08 22:51:39 [error] 2995#0: *307 directory index of "/www/ariang/" is forbidden, client: 192.168.2.20, server: op, request: "GET /ariang/ HTTP/1.1", host: "192.168.2.2", referrer: "http://192.168.2.2/luci/admin/services/aria2/config"
Tue Feb  8 22:51:56 2022 daemon.err uwsgi[2899]: *** has_emperor mode detected (fd: 8) ***
Tue Feb  8 22:51:56 2022 daemon.err uwsgi[2899]: [uWSGI] getting INI configuration from /etc/uwsgi/vassals/luci-cgi_io.ini
Tue Feb  8 22:51:56 2022 daemon.err uwsgi[2899]: Tue Feb  8 22:51:56 2022 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini has been spawned
Tue Feb  8 22:51:56 2022 daemon.err uwsgi[2899]: Tue Feb  8 22:51:56 2022 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini is ready to accept requests
Tue Feb  8 22:51:57 2022 daemon.err uwsgi[2899]: Tue Feb  8 22:51:57 2022 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini is now loyal
Tue Feb  8 22:54:45 2022 daemon.err nginx[2956]: 2022/02/08 22:54:45 [error] 2995#0: *359 directory index of "/www/ariang/" is forbidden, client: 192.168.2.20, server: op, request: "GET /ariang/ HTTP/1.1", host: "192.168.2.2", referrer: "http://192.168.2.2/luci/admin/services/aria2"
Tue Feb  8 22:57:39 2022 daemon.info aria2: Aria2 will run with user 'aria2'.

卸载重装配置还是之前的配置。下载目录权限是0777

**Comment by kiddin9** [comment]
安装 ariang 而不是 ariang-nginx 你是web打不开还是aria2不运行?

**Comment by madman43** [comment]
> 安装 ariang 而不是 ariang-nginx 你是web打不开还是aria2不运行?

我是安装的aria2 不是ng也不是nginx，事运行后打不开web页面，第一次全新安装后是正常打开的，但填写key后直接弹403了

**Comment by kiddin9** [comment]
不知道你说的是什么key, 把 /etc/config/aria2删掉后重新安装luci-app-aria2

**Comment by madman43** [comment]
> 不知道你说的是什么key, 把 /etc/config/aria2删掉后重新安装luci-app-aria2

就是密钥，那我明天试试

**Comment by madman43** [comment]
删除配置文件后重装还是403web页面无法访问

**Comment by madman43** [comment]
我重新使用dd命令全新安装aria2还是报403

**Comment by louis-zhou** [comment]
你试试访问 http://ip/ariang/index.html 看看。

默认点击界面访问的是 http://ip/ariang 缺了 /index.html 。

估计原因是 Ng 没配置默认 index 。

**Comment by madman43** [comment]
> 你试试访问 http://ip/ariang/index.html 看看。
> 
> 默认点击界面访问的是 http://ip/ariang 缺了 /index.html 。
> 
> 估计原因是 Ng 没配置默认 index 。

进去了，但是输入rpc秘钥依旧是未连接，之前通过低版本安装后升级最新版本打开了也是链接上的，下载了两个东西今早起来看就又成那样了，用你的办法进去后无法连接😅

**Comment by madman43** [comment]
> 

嗯嗯

**Comment by madman43** [comment]
> > 你试试访问 http://ip/ariang/index.html 看看。
> > 默认点击界面访问的是 http://ip/ariang 缺了 /index.html 。
> > 估计原因是 Ng 没配置默认 index 。
> 
> 确实有这个问题, /etc/config/nginx 中的ng_index.html 后面加上 index.html 然后service nginx restart 可以解决.

额又有新问题，http模式下输入密码跳转到登录界面。https输入密码正常进入。
这是 /etc/config/nginx 配置信息

`
config main 'global'
	option uci_enable 'true'

config server '_lan'
	list listen '80 default_server'
	list listen '[::]:80 default_server'
	option server_name 'op'
	list include 'conf.d/*.locations'
	option access_log 'off; # logd openwrt'
	option index 'luci index.html index.htm'

config server '_ssl'
	list listen '443 ssl'
	list listen '[::]:443 ssl'
	option server_name '_ssl'
	list include 'conf.d/*.locations'
	option ssl_certificate '/etc/nginx/conf.d/_lan.crt'
	option ssl_certificate_key '/etc/nginx/conf.d/_lan.key'
	option ssl_session_cache 'shared:SSL:32k'
	option ssl_session_timeout '64m'
	option access_log 'off; # logd openwrt'
	option index 'luci index.html index.htm'

config server '_redirect2ssl'

`
