### ISSUE TITLE
homebridge无法启动

### ISSUE THREAD

**Issue by ZhibinLiIntel** [kiddin9/OpenWrt_x86-r2s-r4s#594]
如图，即使勾选了启用并保存应用，homebridge依然是未运行状态，这个插件是不是一直都是不能用的状态呢？
![image](https://user-images.githubusercontent.com/19225626/154850653-8b105177-ac0e-4141-9ff4-70474ff563e2.png)

**Comment by kiddin9** [comment]
没用过这插件, 你可以在这 https://github.com/shanglanxin/luci-app-homebridge 了解下

**Comment by ZhibinLiIntel** [comment]
> 没用过这插件, 你可以在这 https://github.com/shanglanxin/luci-app-homebridge 了解下

这个插件就是集成在opkg源里的那个对吧？尝试了这个在网页的管理界面没办法启动，ssh到路由器后命令行启动，homekit也无法添加bridge，并且官方的homebridge用node安装也后也一样遇到homekit无法添加bridge的问题。

https://github.com/nxhack/openwrt-node-packages 这个repo下的node-homebridge可以正常使用，能正常启动并且IOS的home app可以添加该bridge，搜了一下这个`node-homebridge`在opkg的软件包里也能搜到。

**Comment by kiddin9** [comment]
https://openwrt.org/packages/pkgdata/node-homebridge 是官方库中的.

**Comment by ZhibinLiIntel** [comment]
> https://openwrt.org/packages/pkgdata/node-homebridge 是官方库中的.

谢谢回复。补充一下这个`node-homebridge`没有图形界面，无法在网页管理界面中对应选项，只能从命令行启动然后挂后台。
