### ISSUE TITLE
请问那个固件稳定呢？R4S刷了好几个版本，但是由于插上USB无线网卡就开机扑街了，要么就是启用就扑街了

### ISSUE THREAD

**Issue by zf1976** [kiddin9/OpenWrt_x86-r2s-r4s#595]

**Comment by zf1976** [comment]
comfast cf811ac的

**Comment by refined-fish** [comment]
> comfast cf811ac的

固件原生不支持USB网卡，需要自己加驱动

**Comment by airplayx** [comment]
![image](https://user-images.githubusercontent.com/8004501/170917399-30a88170-039b-4129-8b0f-b797965eaafc.png)
我也是这个网卡，驱动打上提示未激活，一通配置后就无法正常开机了。
您后续怎么解决的？

**Comment by lfcz** [comment]
一样的+1，这个网卡在友善官方的支持文档中，官方的op固件尝试也是只能识别，开启不了无线，换到这个定制固件也是一样的问题，还有可能会开不开机了
