### ISSUE TITLE
[Nginx]配置文件自动刷新为初始状态，导致无法正常SSL访问

### ISSUE THREAD

**Issue by refined-fish** [kiddin9/OpenWrt_x86-r2s-r4s#597]
## 重现步骤:

1. 上传自己的证书和私钥到/etc/nginx/conf.d，替换掉原有的默认_lan.crt和_lan.key。
2. 修改nginx的配置文件，指定新的证书和私钥路径。
3. 重启系统。

## 预期情况:

1. 实现稳定的SSL访问后台页面。

## 实际情况:

1. 重启后确实正常SSL访问。
3. 但是大概过不到一天的时间，会提示不安全。
4. 查证后发现nginx配置文件被刷新回初始状态，且原目录被删除的初始证书和私钥也自动生成了。

## 补充情况:

1. 该问题不是由重启带来的。
2. 修改工具为Xftp上传，配置文件使用记事本打开修改。

## 版本状态:

DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.2'
DISTRIB_REVISION='02.22.2022'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION="OpenWrt 02.22.2022 by Kiddin'"
DISTRIB_TAINTS='busybox'

**Comment by BlackieMei509** [comment]
老哥，在哪里修改nginx的配置文件啊？

**Comment by refined-fish** [comment]
> 老哥，在哪里修改nginx的配置文件啊？

Linux都在config里

**Comment by refined-fish** [comment]
我发现手动安装nginx管理插件包，在插件内修改配置文件的话不会被刷新，但是问题的原因依旧未知
