### ISSUE TITLE
zerotier app error in version 03.03.2022 for x86 

### ISSUE THREAD

**Issue by edwin19861218** [kiddin9/OpenWrt_x86-r2s-r4s#611]
Some erros error after running zerotier-cli or zerotier app:
Error relocating /usr/bin/zerotier-cli: _ZNSt19basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/bin/zerotier-cli: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/bin/zerotier-cli: _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

It seems like a compile error.

I manually installed a lower version and fixed it.
https://downloads.openwrt.org/releases/21.02.2/packages/x86_64/packages/zerotier_1.6.6-2_x86_64.ipk

Plz check, thanks.

**Comment by kiddin9** [comment]
Fixed it.  Downgraded zerotier to 1.6.6-2.
