### ISSUE TITLE
这个openwrt为啥有梦想星城的流量啊？

### ISSUE THREAD

**Issue by wsppxcn** [kiddin9/OpenWrt_x86-r2s-r4s#612]
### 环境
1.爱快一个 192.168.1.1
2.openwrt一个 192.168.1.2
3.win10主机一个 192.168.1.13
都是作为单独一个主机存在，openwrt总是有梦想星城的流量和网易游戏更新的流量，每天都有上传流量！

![image](https://user-images.githubusercontent.com/90166152/156963560-499b871f-81b2-408a-b1d0-5d862d3f1d0d.png)
![image](https://user-images.githubusercontent.com/90166152/156963570-c79c7e64-60fd-4b16-8a32-6f6cb1c9b5ce.png)
![image](https://user-images.githubusercontent.com/90166152/156963628-f594c1ae-a5ff-4e24-ae3d-fc877a992fbf.png)

**Comment by kiddin9** [comment]
换固件.

**Comment by wsppxcn** [comment]
> 

升级了确实没有了，原来的固件是有这种上传的程序吗

**Comment by wsppxcn** [comment]
这种流量更多了。。。 看样子得用别的固件了。

![image](https://user-images.githubusercontent.com/90166152/156976199-13544a44-3e73-4cc2-8734-d0e961c79b6d.png)

**Comment by kiruya1987** [comment]
@wsppxcn 想问下这个监控插件叫什么?  谢谢
