### ISSUE TITLE
本地编译，勾选netdata后编译失败

### ISSUE THREAD

**Issue by MikeMiao** [kiddin9/OpenWrt_x86-r2s-r4s#616]
使用Ubuntu20.0.4编译，梯子处于大陆白名单模式，使用一键编译脚本，勾选了netdata或luci-app-netdata就会编译不成功，取消勾选后可以编译成功
![metdata_fail](https://user-images.githubusercontent.com/17871086/158005512-1cc47292-72b6-49d9-9970-ff9fd010eeab.png)

**Comment by kiddin9** [comment]
已修复, 重新拉取软件包
