### ISSUE TITLE
AdGuard Home 重啟後未啟動

### ISSUE THREAD

**Issue by Stardusstt** [kiddin9/OpenWrt_x86-r2s-r4s#619]
03.03.2022

AdGuard Home 在重啟後未啟動，luci介面設定遺失(e.g.重定向) ，需手動開啟
但AdGuard Home 設定檔存在

**Comment by kiddin9** [comment]
@Stardusstt 已修复,更新luci-app-adguardhome 即可.

**Comment by Stardusstt** [comment]
fix after updated luci-app-adguardhome
