### ISSUE TITLE
8152驱动无法安装, 提示依赖包未提供.

### ISSUE THREAD

**Issue by tonysky2002** [kiddin9/OpenWrt_x86-r2s-r4s#624]
![8152](https://user-images.githubusercontent.com/22363689/159206044-5b22bd42-1129-4c09-a58a-fb1aff96835e.jpg)

**Comment by kiddin9** [comment]
@tonysky2002 已修复.

**Comment by tonysky2002** [comment]
更新了软件包列表后, 依旧是同样提示...

**Comment by kiddin9** [comment]
再试下.

**Comment by tonysky2002** [comment]
可以了, 非常感谢!
