### ISSUE TITLE
nginx允许上传的文件大小太小，超过180M的系统固件没法使用网页更新，上传超过180m文件报错413 Request Entity Too Large

### ISSUE THREAD

**Issue by pzqpeter** [kiddin9/OpenWrt_x86-r2s-r4s#656]
我在https://supes.top/编译的系统大小超过180m了，在使用网页进行新固件写入的时候会报错，无法上传固件到路由器，初步查看问题在于nginx允许上传的文件大小太小

**Comment by kiddin9** [comment]
@pzqpeter 固件tar.gz格式也超过180M了吗

**Comment by pzqpeter** [comment]
是的，我编译的插件和驱动很多，tar.gz的文件大小已经到238M了，可以修改限制大一点吗？以后还有可能需要上传docker镜像，限制设置到600m可以吗？

**Comment by pzqpeter** [comment]
> @pzqpeter下载tar.gz格式也超过180M了



> @pzqpeter下载tar.gz格式也超过180M了
是的，我编译的插件和驱动很多，tar.gz的文件大小已经到238M了，可以修改限制大一点吗？以后还有可能需要上传docker镜像，限制设置到600m可以吗？

**Comment by pzqpeter** [comment]
@kiddin9 

> 是的，我编译的插件和驱动很多，tar.gz的文件大小已经到238M了，可以修改限制大一点吗？以后还有可能需要上传docker镜像，限制设置到600m可以吗？

**Comment by kiddin9** [comment]
你可以修改 /etc/nginx/uci.conf.template  把 client_max_body_size 这行去掉,然后 service nginx restart 即可.

**Comment by pzqpeter** [comment]
修改完合适了，谢谢您

**Comment by MikeMiao** [comment]
还有一个方法，如果/tmp的空间够大，上传到/tmp目录之后可以使用sysupgrade命令直接更新，除了文件名之外不用加任何参数
